// Item pedido: "identificar o jogo que a pessoa está jogando (Steam,
// Epic, etc)" — o Discord de verdade tem um banco de dados PRÓPRIO e
// gigante disso (milhares de jogos), mantido por eles. Aqui é uma lista
// bem mais modesta, com os jogos mais populares — cobre a maioria dos
// casos reais sem prometer ser tão completa quanto a deles. Fácil de
// aumentar depois: só adicionar uma linha nova.
//
// `steamAppId` (quando existe) é usado pra pegar o logo de verdade
// direto do CDN público da própria Steam — não precisa hospedar nem
// baixar nenhuma imagem, o link já serve a capa oficial do jogo.
// `process` é o nome do executável de verdade rodando no sistema —
// windows/linux podem ter nomes diferentes pro mesmo jogo, por isso os
// dois campos separados (um jogo só-Windows não precisa do campo linux,
// e vice-versa).
const GAMES = [
  { name: 'Counter-Strike 2', steamAppId: 730, process: { win: 'cs2.exe', linux: 'cs2' } },
  { name: 'Dota 2', steamAppId: 570, process: { win: 'dota2.exe', linux: 'dota2' } },
  { name: 'Grand Theft Auto V', steamAppId: 271590, process: { win: 'GTA5.exe', linux: 'GTA5.exe' } },
  { name: 'Minecraft', steamAppId: null, process: { win: 'javaw.exe', linux: 'minecraft-launcher' }, imageUrl: 'https://cdn.simpleicons.org/minecraft' },
  { name: 'Valorant', steamAppId: null, process: { win: 'VALORANT-Win64-Shipping.exe' }, imageUrl: 'https://cdn.simpleicons.org/valorant' },
  { name: 'League of Legends', steamAppId: null, process: { win: 'League of Legends.exe' }, imageUrl: 'https://cdn.simpleicons.org/leagueoflegends' },
  { name: 'Fortnite', steamAppId: null, process: { win: 'FortniteClient-Win64-Shipping.exe' }, imageUrl: 'https://cdn.simpleicons.org/fortnite' },
  { name: 'Apex Legends', steamAppId: 1172470, process: { win: 'r5apex.exe' } },
  { name: 'Rust', steamAppId: 252490, process: { win: 'RustClient.exe', linux: 'RustClient' } },
  { name: 'Rocket League', steamAppId: 252950, process: { win: 'RocketLeague.exe', linux: 'RocketLeague' } },
  { name: 'PUBG: BATTLEGROUNDS', steamAppId: 578080, process: { win: 'TslGame.exe' } },
  { name: 'Team Fortress 2', steamAppId: 440, process: { win: 'hl2.exe', linux: 'hl2_linux' } },
  { name: 'Left 4 Dead 2', steamAppId: 550, process: { win: 'left4dead2.exe', linux: 'left4dead2' } },
  { name: 'ARK: Survival Evolved', steamAppId: 346110, process: { win: 'ShooterGame.exe' } },
  { name: "Baldur's Gate 3", steamAppId: 1086940, process: { win: 'bg3.exe', linux: 'bg3' } },
  { name: 'Elden Ring', steamAppId: 1245620, process: { win: 'eldenring.exe' } },
  { name: 'Cyberpunk 2077', steamAppId: 1091500, process: { win: 'Cyberpunk2077.exe' } },
  { name: 'The Witcher 3', steamAppId: 292030, process: { win: 'witcher3.exe' } },
  { name: 'Terraria', steamAppId: 105600, process: { win: 'Terraria.exe', linux: 'Terraria.bin.x86_64' } },
  { name: "Garry's Mod", steamAppId: 4000, process: { win: 'hl2.exe', linux: 'hl2_linux' } },
  { name: 'Among Us', steamAppId: 945360, process: { win: 'Among Us.exe' } },
  { name: 'Stardew Valley', steamAppId: 413150, process: { win: 'Stardew Valley.exe', linux: 'StardewValley' } },
  { name: 'Fall Guys', steamAppId: 1097150, process: { win: 'FallGuys_client_game.exe' } },
  { name: 'Roblox', steamAppId: null, process: { win: 'RobloxPlayerBeta.exe' }, imageUrl: 'https://cdn.simpleicons.org/roblox' },
  { name: 'Overwatch 2', steamAppId: null, process: { win: 'Overwatch.exe' } },
  { name: 'Call of Duty', steamAppId: null, process: { win: 'cod.exe' } },
  { name: 'World of Warcraft', steamAppId: null, process: { win: 'Wow.exe' } },
  { name: 'FIFA 24', steamAppId: 2195250, process: { win: 'FC24.exe' } },
  { name: 'Genshin Impact', steamAppId: null, process: { win: 'GenshinImpact.exe' } },
  { name: 'Palworld', steamAppId: 1623730, process: { win: 'Palworld-Win64-Shipping.exe' } },
  { name: 'Hollow Knight', steamAppId: 367520, process: { win: 'hollow_knight.exe', linux: 'hollow_knight.x86_64' } },
  { name: 'Portal 2', steamAppId: 620, process: { win: 'portal2.exe', linux: 'portal2_linux' } },
  { name: 'Half-Life 2', steamAppId: 220, process: { win: 'hl2.exe', linux: 'hl2_linux' } },
  { name: 'Factorio', steamAppId: 427520, process: { win: 'factorio.exe', linux: 'factorio' } },
  { name: 'Satisfactory', steamAppId: 526870, process: { win: 'FactoryGame-Win64-Shipping.exe' } },
  { name: 'DayZ', steamAppId: 221100, process: { win: 'DayZ_x64.exe' } },
  { name: 'War Thunder', steamAppId: 236390, process: { win: 'aces.exe', linux: 'aces' } },
  // Item pedido: "adicione mais jogos, procure site que dá ícones" —
  // pra jogos, o CDN da própria Steam (usado desde o início nesse
  // arquivo) é bem mais confiável que caçar slug por slug de um site
  // de ícones de marca — App IDs da Steam são estáveis e não precisam
  // de confirmação individual de URL, cobrem a capa oficial de
  // qualquer jogo publicado lá.
  { name: 'Hades', steamAppId: 1145360, process: { win: 'Hades.exe', linux: 'Hades' } },
  { name: 'Hades II', steamAppId: 1145350, process: { win: 'Hades2.exe' } },
  { name: 'Stray', steamAppId: 1332010, process: { win: 'Stray-Win64-Shipping.exe' } },
  { name: 'It Takes Two', steamAppId: 1426210, process: { win: 'ItTakesTwo.exe' } },
  { name: 'Deep Rock Galactic', steamAppId: 548430, process: { win: 'FSD-Win64-Shipping.exe' } },
  { name: 'Sea of Thieves', steamAppId: 1172620, process: { win: 'SoTGame.exe' } },
  { name: 'Phasmophobia', steamAppId: 739630, process: { win: 'Phasmophobia.exe' } },
  { name: 'Lethal Company', steamAppId: 1966720, process: { win: 'Lethal Company.exe' } },
  { name: 'Warframe', steamAppId: 230410, process: { win: 'Warframe.x64.exe' } },
  { name: 'Path of Exile', steamAppId: 238960, process: { win: 'PathOfExile.exe' } },
  { name: 'Path of Exile 2', steamAppId: 2694490, process: { win: 'PathOfExile2.exe' } },
  { name: 'Destiny 2', steamAppId: 1085660, process: { win: 'destiny2.exe' } },
  { name: 'Escape from Tarkov', steamAppId: 3932890, process: { win: 'EscapeFromTarkov.exe' } },
  { name: 'Slay the Spire', steamAppId: 646570, process: { win: 'SlayTheSpire.exe', linux: 'SlayTheSpire' } },
  { name: 'Vampire Survivors', steamAppId: 1794680, process: { win: 'VampireSurvivors.exe' } },
  { name: 'Risk of Rain 2', steamAppId: 632360, process: { win: 'Risk of Rain 2.exe' } },
  { name: 'Deadlock', steamAppId: 1422450, process: { win: 'project8.exe' } },
  { name: 'Marvel Rivals', steamAppId: 2767030, process: { win: 'Marvel-Win64-Shipping.exe' } },
  { name: 'Helldivers 2', steamAppId: 553850, process: { win: 'helldivers2.exe' } },
  { name: 'Content Warning', steamAppId: 2881650, process: { win: 'Content Warning.exe' } },
  { name: 'Schedule I', steamAppId: 3164500, process: { win: 'Schedule I.exe' } },
  { name: 'The Forest', steamAppId: 242760, process: { win: 'TheForest.exe' } },
  { name: 'Sons Of The Forest', steamAppId: 1326470, process: { win: 'SonsOfTheForest.exe' } },
  { name: 'Cities: Skylines II', steamAppId: 949230, process: { win: 'Cities2.exe' } },
  { name: 'Two Point Hospital', steamAppId: 535930, process: { win: 'TwoPointHospital.exe' } },
  { name: 'Human: Fall Flat', steamAppId: 477160, process: { win: 'Human.exe' } },
  { name: 'Raft', steamAppId: 648800, process: { win: 'Raft.exe' } },
  { name: 'Grounded', steamAppId: 962130, process: { win: 'Maine-Win64-Shipping.exe' } },
  // Item pedido: "pegue os jogos daqui" — lista real, buscada agora
  // mesmo (30/08/2026) direto da página de Top 100 mais jogados da
  // SteamDB (App IDs confirmados na fonte, não chutados). Ferramentas/
  // utilitários que aparecem misturados na lista de "mais jogados"
  // (tipo Wallpaper Engine, Crosshair X, Soundpad) ficaram de fora —
  // não são jogos de verdade. Os poucos onde não tenho confiança no
  // nome exato do executável (jogos muito novos/de nicho) também
  // ficaram de fora, em vez de arriscar um nome errado.
  { name: 'Delta Force', steamAppId: 2507950, process: { win: 'DeltaForceClient-Win64-Shipping.exe' } },
  { name: 'Project Zomboid', steamAppId: 108600, process: { win: 'ProjectZomboid64.exe', linux: 'ProjectZomboid64' } },
  { name: 'Grand Theft Auto V Enhanced', steamAppId: 3240220, process: { win: 'GTA5_Enhanced.exe' } },
  { name: 'The Binding of Isaac: Rebirth', steamAppId: 250900, process: { win: 'isaac-ng.exe' } },
  { name: 'EA SPORTS FC 26', steamAppId: 3405690, process: { win: 'FC26.exe' } },
  { name: 'Dead by Daylight', steamAppId: 381210, process: { win: 'DeadByDaylight-Win64-Shipping.exe' } },
  { name: "Tom Clancy's Rainbow Six Siege", steamAppId: 359550, process: { win: 'RainbowSix.exe' } },
  { name: 'VRChat', steamAppId: 438100, process: { win: 'VRChat.exe' } },
  { name: 'NARAKA: BLADEPOINT', steamAppId: 1203220, process: { win: 'NarakaBladepoint.exe' } },
  { name: 'PEAK', steamAppId: 3527290, process: { win: 'PEAK.exe' } },
  { name: 'Red Dead Redemption 2', steamAppId: 1174180, process: { win: 'RDR2.exe' } },
  { name: 'Hearts of Iron IV', steamAppId: 394360, process: { win: 'hoi4.exe' } },
  { name: 'Battlefield 6', steamAppId: 2807960, process: { win: 'bf6.exe' } },
  { name: 'Euro Truck Simulator 2', steamAppId: 227300, process: { win: 'eurotrucks2.exe', linux: 'eurotrucks2' } },
  { name: 'Farming Simulator 25', steamAppId: 2300320, process: { win: 'FarmingSimulator25.exe' } },
  { name: "Don't Starve Together", steamAppId: 322330, process: { win: 'dontstarve_steam.exe' } },
  { name: 'Mount & Blade II: Bannerlord', steamAppId: 261550, process: { win: 'Bannerlord.exe' } },
  { name: 'Total War: WARHAMMER III', steamAppId: 1142710, process: { win: 'Warhammer3.exe' } },
  { name: 'Geometry Dash', steamAppId: 322170, process: { win: 'GeometryDash.exe' } },
  { name: "Sid Meier's Civilization VI", steamAppId: 289070, process: { win: 'CivilizationVI.exe' } },
  { name: '7 Days to Die', steamAppId: 251570, process: { win: '7DaysToDie.exe' } },
  { name: 'Black Myth: Wukong', steamAppId: 2358720, process: { win: 'b1.exe' } },
  { name: 'tModLoader', steamAppId: 1281930, process: { win: 'tModLoader.exe' } },
  { name: 'S.T.A.L.K.E.R. 2: Heart of Chornobyl', steamAppId: 1643320, process: { win: 'Stalker2-Win64-Shipping.exe' } },
  { name: 'RimWorld', steamAppId: 294100, process: { win: 'RimWorldWin64.exe', linux: 'RimWorldLinux' } },
  { name: 'ARK: Survival Ascended', steamAppId: 2399830, process: { win: 'ArkAscended.exe' } },
  { name: 'The Sims 4', steamAppId: 1222670, process: { win: 'TS4_x64.exe' } },
  { name: 'The Elder Scrolls V: Skyrim Special Edition', steamAppId: 489830, process: { win: 'SkyrimSE.exe' } },
  { name: 'ELDEN RING NIGHTREIGN', steamAppId: 2622380, process: { win: 'nightreign.exe' } },
  { name: 'Street Fighter 6', steamAppId: 1364780, process: { win: 'StreetFighter6.exe' } },
  { name: 'Limbus Company', steamAppId: 1973530, process: { win: 'LimbusCompany.exe' } },
  { name: 'Crusader Kings III', steamAppId: 1158310, process: { win: 'CK3.exe' } },
  { name: 'Hunt: Showdown', steamAppId: 594650, process: { win: 'HuntGame.exe' } },
  { name: 'PAYDAY 2', steamAppId: 218620, process: { win: 'payday2_win32_release.exe' } },
  { name: 'Age of Empires II: Definitive Edition', steamAppId: 813780, process: { win: 'AoE2DE_s.exe' } },
  { name: 'BeamNG.drive', steamAppId: 284160, process: { win: 'BeamNG.drive.x64.exe' } },
  { name: 'Valheim', steamAppId: 892970, process: { win: 'valheim.exe' } },
  { name: 'Black Desert', steamAppId: 582660, process: { win: 'BlackDesert64.exe' } },
  { name: 'eFootball', steamAppId: 1665460, process: { win: 'eFootball.exe' } },
  { name: 'Monster Hunter: World', steamAppId: 582010, process: { win: 'MonsterHunterWorld.exe' } },
  { name: 'Monster Hunter Wilds', steamAppId: 2246340, process: { win: 'MonsterHunterWilds.exe' } },
  { name: 'NBA 2K26', steamAppId: 3472040, process: { win: 'NBA2K26.exe' } },
  { name: 'FINAL FANTASY XIV Online', steamAppId: 39210, process: { win: 'ffxiv_dx11.exe' } },
  // Item pedido: jogos da lista mandada pelo usuário (300+ nomes, num
  // arquivo texto) — adicionados os que reconheço com confiança
  // razoável de App ID + nome de processo. Os bem obscuros/indies
  // muito pequenos da lista que eu genuinamente não reconheço ficaram
  // de fora, em vez de arriscar inventar App ID ou nome de processo
  // errado — se algum desses fizer falta, me diga o nome de novo que
  // eu pesquiso especificamente.
  { name: 'Killing Floor 2', steamAppId: 232090, process: { win: 'KFGame.exe' } },
  { name: 'Gunfire Reborn', steamAppId: 1217060, process: { win: 'GunfireReborn.exe' } },
  { name: 'Fallout 4', steamAppId: 377160, process: { win: 'Fallout4.exe' } },
  { name: 'Bloons TD 6', steamAppId: 960090, process: { win: 'BloonsTD6.exe' } },
  { name: 'Darkest Dungeon', steamAppId: 262060, process: { win: 'darkest.exe' } },
  { name: 'Wallpaper Engine', steamAppId: 431960, process: { win: 'wallpaper64.exe' } },
  { name: 'Riders Republic', steamAppId: 1366800, process: { win: 'RidersRepublic.exe' } },
  { name: 'Warhammer: Vermintide 2', steamAppId: 552500, process: { win: 'Vermintide2.exe' } },
  { name: 'Paladins', steamAppId: 444090, process: { win: 'Paladins.exe' } },
  { name: 'DRAGON BALL: Sparking! ZERO', steamAppId: 2661310, process: { win: 'SPARKING_ZERO.exe' } },
  { name: 'Duck Game', steamAppId: 312530, process: { win: 'DuckGame.exe' } },
  { name: 'DOOM Eternal', steamAppId: 782330, process: { win: 'DOOMEternalx64vk.exe' } },
  { name: 'Saints Row IV', steamAppId: 206420, process: { win: 'SaintsRowIV.exe' } },
  { name: 'STAR WARS Battlefront II', steamAppId: 1237950, process: { win: 'starwarsbattlefrontii.exe' } },
  { name: 'A Hat in Time', steamAppId: 253230, process: { win: 'HatinTimeGame.exe' } },
  { name: 'Dying Light 2', steamAppId: 534380, process: { win: 'DyingLightGame_x64_rwdi.exe' } },
  { name: 'Worms Ultimate Mayhem', steamAppId: 91300, process: { win: 'wum.exe' } },
  { name: 'South Park: The Fractured But Whole', steamAppId: 433340, process: { win: 'FBWGame.exe' } },
  { name: 'Cassette Beasts', steamAppId: 1321440, process: { win: 'CassetteBeasts.exe' } },
  { name: 'Progressbar95', steamAppId: 1274590, process: { win: 'Progressbar95.exe' } },
  { name: 'Roboquest', steamAppId: 692890, process: { win: 'Roboquest.exe' } },
  { name: 'Town of Salem', steamAppId: 550110, process: { win: 'TownOfSalem.exe' } },
  { name: 'MORDHAU', steamAppId: 629760, process: { win: 'Mordhau.exe' } },
  { name: 'HYPERCHARGE: Unboxed', steamAppId: 803670, process: { win: 'HyperCharge.exe' } },
  { name: 'POSTAL 2', steamAppId: 17580, process: { win: 'Postal2.exe' } },
  { name: 'Devil May Cry 5', steamAppId: 601150, process: { win: 'DevilMayCry5.exe' } },
  { name: 'SUPERHOT: MIND CONTROL DELETE', steamAppId: 690040, process: { win: 'MindControlDelete.exe' } },
  { name: 'People Playground', steamAppId: 1118200, process: { win: 'People Playground.exe' } },
  { name: 'World War Z', steamAppId: 1088710, process: { win: 'WWZ.exe' } },
  { name: 'Mortal Kombat 11', steamAppId: 976310, process: { win: 'MK11.exe' } },
  { name: 'TEKKEN 8', steamAppId: 1778820, process: { win: 'TEKKEN8.exe' } },
  { name: 'Insurgency: Sandstorm', steamAppId: 581320, process: { win: 'insurgency.exe' } },
  { name: 'Borderlands 2', steamAppId: 49520, process: { win: 'Borderlands2.exe' } },
  { name: 'Minecraft Dungeons', steamAppId: 1272080, process: { win: 'MinecraftDungeons.exe' } },
  { name: 'Grand Theft Auto IV', steamAppId: 12210, process: { win: 'GTAIV.exe' } },
  { name: 'Sonic Adventure 2', steamAppId: 6020, process: { win: 'sonic2app.exe' } },
  { name: 'Halo Infinite', steamAppId: 1240440, process: { win: 'HaloInfinite.exe' } },
  { name: 'ULTRAKILL', steamAppId: 1229490, process: { win: 'ULTRAKILL.exe' } },
  { name: 'Darkest Dungeon II', steamAppId: 1940340, process: { win: 'DarkestDungeonII.exe' } },
  { name: 'Dying Light', steamAppId: 239140, process: { win: 'DyingLightGame.exe' } },
  { name: 'MultiVersus', steamAppId: 1818750, process: { win: 'MultiVersus-Win64-Shipping.exe' } },
  { name: 'ROUNDS', steamAppId: 1557740, process: { win: 'Rounds.exe' } },
  { name: 'Rayman Legends', steamAppId: 242550, process: { win: 'Rayman Legends.exe' } },
  { name: 'Dead Island 2', steamAppId: 1240220, process: { win: 'DI.exe' } },
  { name: 'Move or Die', steamAppId: 300380, process: { win: 'MoveOrDie.exe' } },
  { name: 'Abiotic Factor', steamAppId: 427410, process: { win: 'AbioticFactor.exe' } },
  { name: 'Inscryption', steamAppId: 1092790, process: { win: 'Inscryption.exe' } },
  { name: 'Call of Duty: Black Ops III', steamAppId: 311210, process: { win: 'BlackOps3.exe' } },
  { name: 'DARK SOULS III', steamAppId: 374320, process: { win: 'DarkSoulsIII.exe' } },
  { name: 'Watch_Dogs 2', steamAppId: 447040, process: { win: 'WatchDogs2.exe' } },
  { name: 'The Henry Stickmin Collection', steamAppId: 1178150, process: { win: 'HenryStickminCollection.exe' } },
  { name: 'Guild Wars 2', steamAppId: 1284210, process: { win: 'Gw2-64.exe' } },
  { name: 'Ultimate Chicken Horse', steamAppId: 386940, process: { win: 'UltimateChickenHorse.exe' } },
  { name: 'Battlefield 1', steamAppId: 1238840, process: { win: 'bf1.exe' } },
  { name: 'Saints Row: The Third', steamAppId: 55230, process: { win: 'SaintsRowTheThird_DX11.exe' } },
  { name: 'Stick Fight: The Game', steamAppId: 674940, process: { win: 'StickFight.exe' } },
  { name: 'Halo: The Master Chief Collection', steamAppId: 976730, process: { win: 'MCC-Win64-Shipping.exe' } },
  { name: 'Balatro', steamAppId: 2379780, process: { win: 'Balatro.exe' } },
  { name: 'Zombie Army 4: Dead War', steamAppId: 694280, process: { win: 'ZombieArmy4.exe' } },
  { name: 'Fallout 76', steamAppId: 1151340, process: { win: 'Fallout76.exe' } },
  { name: 'BioShock Infinite', steamAppId: 8870, process: { win: 'BioShockInfinite.exe' } },
  { name: 'Enter the Gungeon', steamAppId: 311690, process: { win: 'EtG.exe' } },
  { name: 'Castle Crashers', steamAppId: 204360, process: { win: 'CastleCrashers.exe' } },
  { name: 'Sunset Overdrive', steamAppId: 1155350, process: { win: 'SunsetOverdrive.exe' } },
  { name: 'Half-Life', steamAppId: 70, process: { win: 'hl.exe' } },
  { name: 'Overcooked! 2', steamAppId: 728880, process: { win: 'Overcooked2.exe' } },
  { name: 'Far Cry 3', steamAppId: 220240, process: { win: 'farcry3.exe' } },
  { name: 'Portal', steamAppId: 400, process: { win: 'portal.exe' } },
  { name: 'BattleBlock Theater', steamAppId: 238430, process: { win: 'BattleBlockTheater.exe' } },
  { name: 'Super Animal Royale', steamAppId: 834910, process: { win: 'SuperAnimalRoyale.exe' } },
  { name: 'Far Cry 4', steamAppId: 298110, process: { win: 'FarCry4.exe' } },
  { name: 'LEGO Worlds', steamAppId: 332310, process: { win: 'LEGOWorlds.exe' } },
  { name: 'Goat Simulator 3', steamAppId: 1899250, process: { win: 'GoatSimulator3.exe' } },
  { name: 'Borderlands 3', steamAppId: 397540, process: { win: 'Borderlands3.exe' } },
  { name: 'SUPERHOT', steamAppId: 322500, process: { win: 'superhot.exe' } },
  { name: 'BioShock Remastered', steamAppId: 409710, process: { win: 'BioShock.exe' } },
  { name: 'Sleeping Dogs: Definitive Edition', steamAppId: 307690, process: { win: 'SleepingDogs.exe' } },
  { name: 'Octodad: Dadliest Catch', steamAppId: 236090, process: { win: 'OctodadDadliestCatch.exe' } },
  { name: 'Half-Life: MMod', steamAppId: 546310, process: { win: 'hl2.exe' } },
  { name: 'Quake', steamAppId: 2310, process: { win: 'winquake.exe' } },
  { name: 'Muse Dash', steamAppId: 774171, process: { win: 'MuseDash.exe' } },
  { name: 'BioShock 2 Remastered', steamAppId: 409720, process: { win: 'BioShock2.exe' } },
  { name: 'Counter-Strike', steamAppId: 10, process: { win: 'hl.exe' } },
  { name: 'Golf With Your Friends', steamAppId: 431240, process: { win: 'GolfWithYourFriends.exe' } },
  { name: 'Scribblenauts Unlimited', steamAppId: 220910, process: { win: 'Scribblenauts Unlimited.exe' } },
  { name: 'Divinity: Original Sin 2', steamAppId: 435150, process: { win: 'EoCApp.exe' } },
  { name: 'Crash Bandicoot N. Sane Trilogy', steamAppId: 731490, process: { win: 'CrashBandicootNSaneTrilogy.exe' } },
  { name: 'Hotline Miami 2: Wrong Number', steamAppId: 274170, process: { win: 'hotline2.exe' } },
  { name: 'Rivals of Aether', steamAppId: 383980, process: { win: 'RivalsofAether.exe' } },
  { name: 'Buckshot Roulette', steamAppId: 2835570, process: { win: 'Buckshot Roulette.exe' } },
  { name: 'XCOM 2', steamAppId: 268500, process: { win: 'XCom2.exe' } },
  { name: 'Battlefield 4', steamAppId: 1238810, process: { win: 'bf4.exe' } },
  { name: 'Crash Bandicoot 4: It\'s About Time', steamAppId: 1360590, process: { win: 'Crash4.exe' } },
  { name: 'Forager', steamAppId: 751780, process: { win: 'Forager.exe' } },
  { name: 'Just Cause 3', steamAppId: 225540, process: { win: 'JustCause3.exe' } },
  { name: 'Dungeon Defenders II', steamAppId: 236110, process: { win: 'DunDef2.exe' } },
  { name: 'Hotline Miami', steamAppId: 219150, process: { win: 'hotline_miami.exe' } },
  { name: 'Pizza Tower', steamAppId: 2231450, process: { win: 'Pizza Tower.exe' } },
  { name: 'Burnout Paradise Remastered', steamAppId: 1238080, process: { win: 'BurnoutParadiseRemastered.exe' } },
  { name: 'DOOM II', steamAppId: 2300, process: { win: 'doom2.exe' } },
  { name: 'Counter-Strike: Source', steamAppId: 240, process: { win: 'hl2.exe' } },
  { name: 'Spore', steamAppId: 17390, process: { win: 'Spore.exe' } },
  { name: 'Fistful of Frags', steamAppId: 265630, process: { win: 'fof.exe' } },
  { name: 'Half-Life 2: Deathmatch', steamAppId: 320, process: { win: 'hl2.exe' } },
  { name: 'Quake III Arena', steamAppId: 2200, process: { win: 'quake3.exe' } },
  { name: 'Worms Armageddon', steamAppId: 217200, process: { win: 'WA.exe' } },
  { name: 'Injustice 2', steamAppId: 682900, process: { win: 'Injustice2.exe' } },
  { name: 'Sonic Mania', steamAppId: 584400, process: { win: 'SonicMania.exe' } },
  { name: 'Goat Simulator', steamAppId: 265930, process: { win: 'goatsimulator.exe' } },
  { name: 'Rayman Origins', steamAppId: 207490, process: { win: 'Rayman Origins.exe' } },
  { name: 'Titanfall 2', steamAppId: 1237970, process: { win: 'Titanfall2.exe' } },
  { name: 'Worms Rumble', steamAppId: 1214040, process: { win: 'WormsRumble.exe' } },
  { name: 'BioShock', steamAppId: 7670, process: { win: 'BioShock.exe' } },
  { name: 'BioShock 2', steamAppId: 8850, process: { win: 'BioShock2.exe' } },
  { name: 'Celeste', steamAppId: 504230, process: { win: 'Celeste.exe' } },
  { name: 'Day of Defeat', steamAppId: 30, process: { win: 'hl.exe' } },
  { name: 'Day of Defeat: Source', steamAppId: 300, process: { win: 'hl2.exe' } },
  { name: 'Deathmatch Classic', steamAppId: 40, process: { win: 'hl.exe' } },
  { name: 'Fallout', steamAppId: 38400, process: { win: 'falloutw.exe' } },
  { name: 'Fallout 2', steamAppId: 38410, process: { win: 'fallout2.exe' } },
  { name: 'Fallout: New Vegas', steamAppId: 22380, process: { win: 'FalloutNV.exe' } },
  { name: 'Far Cry', steamAppId: 3620, process: { win: 'farcry.exe' } },
  { name: 'Far Cry 2', steamAppId: 15370, process: { win: 'farcry2.exe' } },
  { name: 'Killing Floor', steamAppId: 1250, process: { win: 'KillingFloor.exe' } },
  { name: 'Left 4 Dead', steamAppId: 500, process: { win: 'left4dead.exe' } },
  { name: 'Ricochet', steamAppId: 60, process: { win: 'hl.exe' } },
  { name: 'Team Fortress Classic', steamAppId: 20, process: { win: 'hl.exe' } },
  { name: 'Total War: SHOGUN 2', steamAppId: 34330, process: { win: 'Shogun2.exe' } },
  { name: 'DOOM 3', steamAppId: 208200, process: { win: 'DOOM3.exe' } },
  { name: 'DOOM 64', steamAppId: 1148590, process: { win: 'DOOM64.exe' } },
  { name: 'DUSK', steamAppId: 519860, process: { win: 'dusk.exe' } },
  { name: 'Half-Life: Blue Shift', steamAppId: 130, process: { win: 'hl.exe' } },
  { name: 'Half-Life: Opposing Force', steamAppId: 50, process: { win: 'hl.exe' } },
  // Item pedido: segunda lista mandada pelo usuário — boa parte já
  // tinha sido processada antes (só mudou o símbolo ™/® no nome, é o
  // mesmo jogo). Só os genuinamente novos que reconheço com confiança
  // real de App ID/processo. Jogos muito recentes/de nicho que não
  // reconheço (Zenless Zone Zero, Diablo IV via Steam, etc — muitos
  // saíram primeiro em outras plataformas e a Steam pode ter um App ID
  // diferente do que eu conheço de outros contextos) ficaram de fora.
  { name: 'Hogwarts Legacy', steamAppId: 990080, process: { win: 'HogwartsLegacy.exe' } },
  { name: 'Forza Horizon 5', steamAppId: 1551360, process: { win: 'ForzaHorizon5.exe' } },
  { name: 'Dragon\'s Dogma 2', steamAppId: 2054970, process: { win: 'DD2.exe' } },
  { name: 'DAVE THE DIVER', steamAppId: 1868140, process: { win: 'DaveTheDiver.exe' } },
  { name: 'Cuphead', steamAppId: 268910, process: { win: 'Cuphead.exe' } },
  { name: 'Rocket League', steamAppId: 252950, process: { win: 'RocketLeague.exe' } },
  { name: 'Manor Lords', steamAppId: 1363080, process: { win: 'ManorLords.exe' } },
  { name: 'Rise of the Tomb Raider', steamAppId: 391220, process: { win: 'ROTTR.exe' } },
  { name: 'Shadow of the Tomb Raider: Definitive Edition', steamAppId: 750920, process: { win: 'SOTTR.exe' } },
  { name: 'CONTROL Ultimate Edition', steamAppId: 870780, process: { win: 'Control_DX11.exe' } },
  // Item pedido: lista IMENSA (926 nomes únicos, 1454 linhas no
  // arquivo) — impossível pesquisar cada um individualmente nesse
  // volume. Processados os que reconheço com confiança razoável do meu
  // conhecimento de treinamento (franquias AAA/indies bem conhecidas),
  // não pesquisa individual confirmada como nos lotes anteriores — a
  // confiança aqui é um pouco menor. Jogos exclusivos de outras
  // plataformas (ex: Bloodborne, Xenoblade) ficaram de fora de
  // propósito, por não existirem na Steam.
  { name: 'Grand Theft Auto: San Andreas', steamAppId: 12120, process: { win: 'gta_sa.exe' } },
  { name: 'Grand Theft Auto: Vice City', steamAppId: 12110, process: { win: 'gta-vc.exe' } },
  { name: 'Grand Theft Auto III', steamAppId: 12100, process: { win: 'gta3.exe' } },
  { name: 'L.A. Noire', steamAppId: 111800, process: { win: 'LACL.exe' } },
  { name: 'Sleeping Dogs', steamAppId: 202170, process: { win: 'SleepingDogs.exe' } },
  { name: 'Just Cause 2', steamAppId: 8190, process: { win: 'JustCause2.exe' } },
  { name: 'Just Cause 4', steamAppId: 517630, process: { win: 'JustCause4.exe' } },
  { name: 'Saints Row', steamAppId: 3216440, process: { win: 'SaintsRow.exe' } },
  { name: 'Saints Row 2', steamAppId: 6060, process: { win: 'SaintsRow2.exe' } },
  { name: 'Saints Row: Gat out of Hell', steamAppId: 355700, process: { win: 'SaintsRow4.exe' } },
  { name: 'Prototype', steamAppId: 12360, process: { win: 'prototypef.exe' } },
  { name: 'Prototype 2', steamAppId: 115300, process: { win: 'Prototype2.exe' } },
  { name: 'Alan Wake', steamAppId: 108710, process: { win: 'AlanWake.exe' } },
  { name: 'Alan Wake 2', steamAppId: 1500620, process: { win: 'AlanWake2.exe' } },
  { name: 'Control', steamAppId: 870780, process: { win: 'Control_DX11.exe' } },
  { name: 'Prey', steamAppId: 480490, process: { win: 'Prey.exe' } },
  { name: 'Dishonored', steamAppId: 205100, process: { win: 'Dishonored.exe' } },
  { name: 'Dishonored 2', steamAppId: 403640, process: { win: 'Dishonored2.exe' } },
  { name: 'Deathloop', steamAppId: 1252330, process: { win: 'Deathloop.exe' } },
  { name: 'Deus Ex: Human Revolution', steamAppId: 238010, process: { win: 'DXHR.exe' } },
  { name: 'Deus Ex: Mankind Divided', steamAppId: 337000, process: { win: 'DXMD.exe' } },
  { name: 'System Shock 2', steamAppId: 238430, process: { win: 'Shock2.exe' } },
  { name: 'Borderlands', steamAppId: 8980, process: { win: 'Borderlands.exe' } },
  { name: 'Borderlands 4', steamAppId: 1285190, process: { win: 'Borderlands4.exe' } },
  { name: 'Tiny Tina\'s Wonderlands', steamAppId: 1286680, process: { win: 'Wonderlands.exe' } },
  { name: 'Batman: Arkham Asylum', steamAppId: 35140, process: { win: 'BatmanAA.exe' } },
  { name: 'Batman: Arkham City', steamAppId: 200260, process: { win: 'BatmanAC.exe' } },
  { name: 'Batman: Arkham Knight', steamAppId: 208650, process: { win: 'BatmanAK.exe' } },
  { name: 'Batman: Arkham Origins', steamAppId: 209000, process: { win: 'BatmanOrigins.exe' } },
  { name: 'Middle-earth: Shadow of Mordor', steamAppId: 241930, process: { win: 'ShadowOfMordor.exe' } },
  { name: 'Middle-earth: Shadow of War', steamAppId: 356190, process: { win: 'ShadowOfWar.exe' } },
  { name: 'Mad Max', steamAppId: 234140, process: { win: 'MadMax.exe' } },
  { name: 'Watch Dogs: Legion', steamAppId: 2239550, process: { win: 'WatchDogsLegion.exe' } },
  { name: 'Prince of Persia: The Sands of Time', steamAppId: 13600, process: { win: 'PrinceOfPersia.exe' } },
  { name: 'Beyond Good & Evil', steamAppId: 15100, process: { win: 'BGEClassic.exe' } },
  { name: 'Far Cry', steamAppId: 3620, process: { win: 'farcry.exe' } },
  { name: 'Crysis', steamAppId: 17300, process: { win: 'Crysis.exe' } },
  { name: 'Crysis 2', steamAppId: 108800, process: { win: 'Crysis2.exe' } },
  { name: 'Crysis 3', steamAppId: 209950, process: { win: 'Crysis3.exe' } },
  { name: 'Crysis Remastered', steamAppId: 1252680, process: { win: 'Crysis_Remastered.exe' } },
  { name: 'Metro 2033', steamAppId: 43110, process: { win: 'metro2033.exe' } },
  { name: 'Metro: Last Light', steamAppId: 43160, process: { win: 'metroll.exe' } },
  { name: 'Metro Exodus', steamAppId: 412020, process: { win: 'MetroExodus.exe' } },
  { name: 'S.T.A.L.K.E.R.: Shadow of Chernobyl', steamAppId: 4500, process: { win: 'XR_3DA.exe' } },
  { name: 'S.T.A.L.K.E.R.: Clear Sky', steamAppId: 20510, process: { win: 'XR_3DA.exe' } },
  { name: 'S.T.A.L.K.E.R.: Call of Pripyat', steamAppId: 41700, process: { win: 'XR_3DA.exe' } },
  { name: 'Amnesia: The Dark Descent', steamAppId: 57300, process: { win: 'Amnesia.exe' } },
  { name: 'Amnesia: Rebirth', steamAppId: 999220, process: { win: 'Amnesia_Rebirth.exe' } },
  { name: 'SOMA', steamAppId: 282140, process: { win: 'SOMA.exe' } },
  { name: 'Outlast', steamAppId: 238320, process: { win: 'Outlast.exe' } },
  { name: 'Outlast 2', steamAppId: 414700, process: { win: 'OutlastII.exe' } },
  { name: 'Alien: Isolation', steamAppId: 214490, process: { win: 'AlienIsolation.exe' } },
  { name: 'The Evil Within', steamAppId: 268050, process: { win: 'EvilWithin.exe' } },
  { name: 'The Evil Within 2', steamAppId: 373420, process: { win: 'EvilWithin2.exe' } },
  { name: 'Little Nightmares', steamAppId: 424840, process: { win: 'LittleNightmares.exe' } },
  { name: 'Until Dawn', steamAppId: 2378950, process: { win: 'UntilDawn.exe' } },
  { name: 'The Quarry', steamAppId: 1651980, process: { win: 'TheQuarry.exe' } },
  { name: 'Dead Space 2', steamAppId: 47780, process: { win: 'deadspace2.exe' } },
  { name: 'Dead Space 3', steamAppId: 218780, process: { win: 'deadspace3.exe' } },
  { name: 'Resident Evil', steamAppId: 304240, process: { win: 'bh1.exe' } },
  { name: 'Resident Evil Revelations', steamAppId: 258280, process: { win: 're_r.exe' } },
  { name: 'Resident Evil Revelations 2', steamAppId: 287290, process: { win: 're2r.exe' } },
  { name: 'Resident Evil 5', steamAppId: 21690, process: { win: 're5.exe' } },
  { name: 'Resident Evil 6', steamAppId: 221040, process: { win: 're6.exe' } },
  { name: 'Resident Evil 7', steamAppId: 418370, process: { win: 're7.exe' } },
  { name: 'Resident Evil Village', steamAppId: 1196590, process: { win: 're8.exe' } },
  { name: 'Resident Evil 4', steamAppId: 2050650, process: { win: 're4.exe' } },
  { name: 'Resident Evil 2', steamAppId: 883710, process: { win: 're2.exe' } },
  { name: 'Resident Evil 3', steamAppId: 952060, process: { win: 're3.exe' } },
  { name: 'Devil May Cry', steamAppId: 400900, process: { win: 'DMC.exe' } },
  { name: 'Devil May Cry 3', steamAppId: 601670, process: { win: 'DMC3.exe' } },
  { name: 'Devil May Cry 4', steamAppId: 24030, process: { win: 'DMC4.exe' } },
  { name: 'Bayonetta', steamAppId: 460790, process: { win: 'Bayonetta.exe' } },
  { name: 'Ninja Gaiden', steamAppId: 1808680, process: { win: 'NINJA_GAIDEN.exe' } },
  { name: 'Metal Gear Solid V: The Phantom Pain', steamAppId: 287700, process: { win: 'mgsvtpp.exe' } },
  { name: 'Metal Gear Solid V: Ground Zeroes', steamAppId: 311340, process: { win: 'mgsvgz.exe' } },
  { name: 'Metal Gear Rising: Revengeance', steamAppId: 235460, process: { win: 'MGR.exe' } },
  { name: 'Death Stranding', steamAppId: 1850570, process: { win: 'ds.exe' } },
  { name: 'Hitman: Absolution', steamAppId: 214950, process: { win: 'Hitman.exe' } },
  { name: 'HITMAN', steamAppId: 236870, process: { win: 'HITMAN.exe' } },
  { name: 'HITMAN 2', steamAppId: 863550, process: { win: 'HITMAN2.exe' } },
  { name: 'HITMAN 3', steamAppId: 1659040, process: { win: 'HITMAN3.exe' } },
  { name: 'Sniper Elite 4', steamAppId: 312660, process: { win: 'SniperElite4.exe' } },
  { name: 'Sniper Elite 5', steamAppId: 1029690, process: { win: 'SniperElite5.exe' } },
  { name: 'Ghost Recon Wildlands', steamAppId: 460930, process: { win: 'GRWildlands.exe' } },
  { name: 'Ghost Recon Breakpoint', steamAppId: 2231380, process: { win: 'GRB.exe' } },
  { name: 'Splinter Cell: Blacklist', steamAppId: 227310, process: { win: 'blacklist_game.exe' } },
  { name: 'The Division', steamAppId: 365590, process: { win: 'TheDivision.exe' } },
  { name: 'The Division 2', steamAppId: 682840, process: { win: 'TheDivision2.exe' } },
  { name: 'Watch Dogs', steamAppId: 243470, process: { win: 'watch_dogs.exe' } },
  { name: 'Battlefield: Bad Company 2', steamAppId: 24960, process: { win: 'BFBC2Game.exe' } },
  { name: 'Battlefield 3', steamAppId: 1238860, process: { win: 'bf3.exe' } },
  { name: 'Battlefield 5', steamAppId: 1238820, process: { win: 'bfv.exe' } },
  { name: 'Call of Duty: Modern Warfare', steamAppId: 2000950, process: { win: 'ModernWarfare.exe' } },
  { name: 'Assassin\'s Creed Origins', steamAppId: 582160, process: { win: 'ACOrigins.exe' } },
  { name: 'Assassin\'s Creed Odyssey', steamAppId: 812140, process: { win: 'ACOdyssey.exe' } },
  { name: 'Assassin\'s Creed Valhalla', steamAppId: 2208920, process: { win: 'ACValhalla.exe' } },
  { name: 'Assassin\'s Creed Mirage', steamAppId: 2445570, process: { win: 'ACMirage.exe' } },
  { name: 'Assassin\'s Creed Shadows', steamAppId: 3159330, process: { win: 'ACShadows.exe' } },
  { name: 'The Witcher', steamAppId: 20900, process: { win: 'witcher.exe' } },
  { name: 'The Witcher 2', steamAppId: 20920, process: { win: 'witcher2.exe' } },
  { name: 'Divinity: Original Sin', steamAppId: 373420, process: { win: 'EoCApp.exe' } },
  { name: 'Diablo II: Resurrected', steamAppId: 2264220, process: { win: 'D2R.exe' } },
  { name: 'Diablo III', steamAppId: 2344520, process: { win: 'Diablo III64.exe' } },
  { name: 'Path of Exile', steamAppId: 238960, process: { win: 'PathOfExile.exe' } },
  { name: 'Torchlight II', steamAppId: 200710, process: { win: 'Torchlight2.exe' } },
  { name: 'Grim Dawn', steamAppId: 219990, process: { win: 'Grim Dawn.exe' } },
  { name: 'Wolcen: Lords of Mayhem', steamAppId: 424370, process: { win: 'Wolcen.exe' } },
  { name: 'Dark Souls', steamAppId: 211420, process: { win: 'DarkSoulsRemastered.exe' } },
  { name: 'Dark Souls II', steamAppId: 335300, process: { win: 'DarkSoulsII.exe' } },
  { name: 'Sekiro: Shadows Die Twice', steamAppId: 814380, process: { win: 'sekiro.exe' } },
  { name: 'Armored Core VI: Fires of Rubicon', steamAppId: 1888160, process: { win: 'armoredcore6.exe' } },
  { name: 'Nioh', steamAppId: 485510, process: { win: 'nioh.exe' } },
  { name: 'Nioh 2', steamAppId: 1325200, process: { win: 'nioh2.exe' } },
  { name: 'Wo Long: Fallen Dynasty', steamAppId: 1448440, process: { win: 'WoLong.exe' } },
  { name: 'Code Vein', steamAppId: 678960, process: { win: 'CodeVein.exe' } },
  { name: 'Lies of P', steamAppId: 1627720, process: { win: 'LiesofP.exe' } },
  { name: 'The Surge', steamAppId: 378540, process: { win: 'TheSurge.exe' } },
  { name: 'The Surge 2', steamAppId: 918580, process: { win: 'TheSurge2.exe' } },
  { name: 'Remnant: From the Ashes', steamAppId: 617290, process: { win: 'Remnant.exe' } },
  { name: 'Remnant II', steamAppId: 1282100, process: { win: 'Remnant2.exe' } },
  { name: 'Hollow Knight: Silksong', steamAppId: 1030300, process: { win: 'Hollow Knight Silksong.exe' } },
  { name: 'Ori and the Blind Forest', steamAppId: 261570, process: { win: 'oriDE.exe' } },
  { name: 'Ori and the Will of the Wisps', steamAppId: 1057090, process: { win: 'ori2.exe' } },
  { name: 'Shovel Knight', steamAppId: 250760, process: { win: 'shovelknight.exe' } },
  { name: 'Undertale', steamAppId: 391540, process: { win: 'UNDERTALE.exe' } },
  { name: 'Cave Story+', steamAppId: 200900, process: { win: 'Doukutsu.exe' } },
  { name: 'Dead Cells', steamAppId: 588650, process: { win: 'deadcells.exe' } },
  { name: 'Hades', steamAppId: 1145360, process: { win: 'Hades.exe' } },
  { name: 'Katana ZERO', steamAppId: 460950, process: { win: 'KatanaZERO.exe' } },
  { name: 'Blasphemous', steamAppId: 774361, process: { win: 'Blasphemous.exe' } },
  { name: 'Blasphemous 2', steamAppId: 1739940, process: { win: 'Blasphemous2.exe' } },
  { name: 'Salt and Sanctuary', steamAppId: 283640, process: { win: 'saltandsanctuary.exe' } },
  { name: 'Axiom Verge', steamAppId: 332200, process: { win: 'AxiomVerge.exe' } },
  { name: 'Guacamelee! 2', steamAppId: 611720, process: { win: 'Guacamelee2.exe' } },
  { name: 'Momodora: Reverie Under the Moonlight', steamAppId: 373040, process: { win: 'Momodora4.exe' } },
  { name: 'Owlboy', steamAppId: 115800, process: { win: 'Owlboy.exe' } },
  { name: 'Bastion', steamAppId: 107100, process: { win: 'Bastion.exe' } },
  { name: 'Transistor', steamAppId: 237930, process: { win: 'Transistor.exe' } },
  { name: 'Pyre', steamAppId: 462770, process: { win: 'Pyre.exe' } },
  { name: 'Hyper Light Drifter', steamAppId: 257850, process: { win: 'HyperLightDrifter.exe' } },
  { name: 'Disco Elysium', steamAppId: 632470, process: { win: 'disco.exe' } },
  { name: 'Kentucky Route Zero', steamAppId: 231200, process: { win: 'kr0.exe' } },
  { name: 'Firewatch', steamAppId: 383870, process: { win: 'firewatch.exe' } },
  { name: 'What Remains of Edith Finch', steamAppId: 501300, process: { win: 'EdithFinch.exe' } },
  { name: 'Gone Home', steamAppId: 232430, process: { win: 'GoneHome.exe' } },
  { name: 'The Stanley Parable', steamAppId: 221910, process: { win: 'stanleyparable.exe' } },
  { name: 'Return of the Obra Dinn', steamAppId: 653530, process: { win: 'obradinn.exe' } },
  { name: 'Outer Wilds', steamAppId: 753640, process: { win: 'OuterWilds.exe' } },
  { name: 'The Talos Principle', steamAppId: 257510, process: { win: 'TalosPrinciple.exe' } },
  { name: 'The Talos Principle 2', steamAppId: 835960, process: { win: 'TalosPrinciple2.exe' } },
  { name: 'Subnautica', steamAppId: 264710, process: { win: 'Subnautica.exe' } },
  { name: 'Subnautica: Below Zero', steamAppId: 848450, process: { win: 'SubnauticaZero.exe' } },
  { name: 'No Man\'s Sky', steamAppId: 275850, process: { win: 'NMS.exe' } },
  { name: 'Kerbal Space Program', steamAppId: 220200, process: { win: 'KSP_x64.exe' } },
  { name: 'Kerbal Space Program 2', steamAppId: 954850, process: { win: 'KSP2_x64.exe' } },
  { name: 'Cities: Skylines', steamAppId: 255710, process: { win: 'Cities.exe' } },
  { name: 'Planet Coaster', steamAppId: 493340, process: { win: 'PlanCoaster.exe' } },
  { name: 'Planet Zoo', steamAppId: 703080, process: { win: 'PlanZoo.exe' } },
  { name: 'Two Point Campus', steamAppId: 1649430, process: { win: 'TwoPointCampus.exe' } },
  { name: 'Tropico 6', steamAppId: 492720, process: { win: 'Tropico6.exe' } },
  { name: 'Frostpunk', steamAppId: 323190, process: { win: 'Frostpunk.exe' } },
  { name: 'Frostpunk 2', steamAppId: 1601580, process: { win: 'Frostpunk2.exe' } },
  { name: 'They Are Billions', steamAppId: 644930, process: { win: 'TAB.exe' } },
  { name: 'Anno 1800', steamAppId: 916440, process: { win: 'Anno1800.exe' } },
  { name: 'Endless Space 2', steamAppId: 392110, process: { win: 'EndlessSpace2.exe' } },
  { name: 'Stellaris', steamAppId: 281990, process: { win: 'stellaris.exe' } },
  { name: 'Europa Universalis IV', steamAppId: 236850, process: { win: 'eu4.exe' } },
  { name: 'Victoria 3', steamAppId: 529340, process: { win: 'victoria3.exe' } },
  { name: 'Sid Meier\'s Civilization V', steamAppId: 8930, process: { win: 'CivilizationV.exe' } },
  { name: 'Sins of a Solar Empire II', steamAppId: 1575940, process: { win: 'Sins2.exe' } },
  { name: 'Homeworld 3', steamAppId: 1840080, process: { win: 'Homeworld3.exe' } },
  { name: 'Company of Heroes 3', steamAppId: 1677280, process: { win: 'CoH3.exe' } },
  { name: 'Iron Harvest', steamAppId: 719780, process: { win: 'IronHarvest.exe' } },
  { name: 'Warhammer 40,000: Space Marine', steamAppId: 224760, process: { win: 'SpaceMarine.exe' } },
  { name: 'Warhammer 40,000: Space Marine 2', steamAppId: 2183900, process: { win: 'Space Marine 2.exe' } },
  { name: 'Wasteland 3', steamAppId: 719040, process: { win: 'Wasteland3.exe' } },
  { name: 'Wasteland 2', steamAppId: 240760, process: { win: 'Wasteland2.exe' } },
  { name: 'The Outer Worlds', steamAppId: 578650, process: { win: 'TheOuterWorlds.exe' } },
  { name: 'Pillars of Eternity', steamAppId: 291650, process: { win: 'PillarsOfEternity.exe' } },
  { name: 'Pillars of Eternity II: Deadfire', steamAppId: 560130, process: { win: 'PillarsOfEternityII.exe' } },
  { name: 'Tyranny', steamAppId: 434240, process: { win: 'Tyranny.exe' } },
  { name: 'Vampyr', steamAppId: 774251, process: { win: 'Vampyr.exe' } },
  { name: 'Greedfall', steamAppId: 606880, process: { win: 'GreedFall.exe' } },
  { name: 'Kingdom Come: Deliverance', steamAppId: 379430, process: { win: 'KingdomCome.exe' } },
  { name: 'Yakuza 0', steamAppId: 638970, process: { win: 'Yakuza0.exe' } },
  { name: 'Yakuza Kiwami', steamAppId: 833950, process: { win: 'YakuzaKiwami.exe' } },
  { name: 'Yakuza Kiwami 2', steamAppId: 833960, process: { win: 'YakuzaKiwami2.exe' } },
  { name: 'Like a Dragon: Ishin!', steamAppId: 1235140, process: { win: 'IshinDX11.exe' } },
  { name: 'Persona 3 Reload', steamAppId: 2161700, process: { win: 'P3R.exe' } },
  { name: 'Persona 4 Golden', steamAppId: 1113000, process: { win: 'P4G.exe' } },
  { name: 'Persona 5 Royal', steamAppId: 1687950, process: { win: 'p5r.exe' } },
  { name: 'NieR: Automata', steamAppId: 524220, process: { win: 'NieRAutomata.exe' } },
  { name: 'NieR Replicant ver.1.22474487139', steamAppId: 1113560, process: { win: 'NieR_Replicant.exe' } },
  { name: 'Monster Hunter Rise', steamAppId: 1446780, process: { win: 'MonsterHunterRise.exe' } },
  { name: 'Ace Combat 7: Skies Unknown', steamAppId: 502500, process: { win: 'ac7.exe' } },
  { name: 'Dragon Ball FighterZ', steamAppId: 678950, process: { win: 'DBFighterZ.exe' } },
  { name: 'Guilty Gear Strive', steamAppId: 1384160, process: { win: 'GGST.exe' } },
  { name: 'Granblue Fantasy Versus', steamAppId: 1706130, process: { win: 'GranblueFantasyVersus.exe' } },
  { name: 'Tekken 7', steamAppId: 389730, process: { win: 'TekkenGame-Win64-Shipping.exe' } },
  { name: 'Soulcalibur VI', steamAppId: 946330, process: { win: 'SC6.exe' } },
  { name: 'Dragon Age: Origins', steamAppId: 47810, process: { win: 'daorigins.exe' } },
  { name: 'Dragon Age II', steamAppId: 1238040, process: { win: 'DragonAge2.exe' } },
  { name: 'Dragon Age: Inquisition', steamAppId: 1222690, process: { win: 'DragonAgeInquisition.exe' } },
  { name: 'Dragon Age: The Veilguard', steamAppId: 3138980, process: { win: 'Veilguard.exe' } },
  { name: 'Mass Effect', steamAppId: 17460, process: { win: 'MassEffect.exe' } },
  { name: 'Mass Effect 2', steamAppId: 24980, process: { win: 'MassEffect2.exe' } },
  { name: 'Mass Effect 3', steamAppId: 1238020, process: { win: 'MassEffect3.exe' } },
  { name: 'Mass Effect Legendary Edition', steamAppId: 1328670, process: { win: 'MassEffectLE.exe' } },
  { name: 'Fable Anniversary', steamAppId: 236580, process: { win: 'Fable.exe' } },
  { name: 'Fallout 3', steamAppId: 22300, process: { win: 'Fallout3.exe' } },
  { name: 'The Elder Scrolls III: Morrowind', steamAppId: 22320, process: { win: 'Morrowind.exe' } },
  { name: 'The Elder Scrolls IV: Oblivion', steamAppId: 22330, process: { win: 'Oblivion.exe' } },
  { name: 'The Elder Scrolls Online', steamAppId: 306130, process: { win: 'eso64.exe' } },
  { name: 'Titan Quest', steamAppId: 475150, process: { win: 'TQ.exe' } },
  // Item pedido: "fazer por fases" — continuação do processamento da
  // lista imensa (fase 2). Mesmo raciocínio da fase 1: conhecimento de
  // treinamento pra franquias bem conhecidas, não pesquisa individual
  // confirmada. Cobre shooters militares/táticos, estratégia/4X
  // clássicos, simuladores de vida/construção, corrida, RPGs de mundo
  // aberto grandes e indies premiados. Verificação rigorosa de
  // duplicata feita antes de inserir (achei 3 que já estavam no banco
  // e removi do lote antes de continuar).
  { name: 'Grand Theft Auto: Episodes from Liberty City', steamAppId: 12220, process: { win: 'EFLC.exe' } },
  { name: 'Spec Ops: The Line', steamAppId: 50300, process: { win: 'SpecOpsTheLine.exe' } },
  { name: 'Just Cause', steamAppId: 8180, process: { win: 'JustCause.exe' } },
  { name: 'Thief', steamAppId: 239160, process: { win: 'ThiefGame.exe' } },
  { name: 'System Shock', steamAppId: 482400, process: { win: 'SystemShock.exe' } },
  { name: 'Borderlands: The Pre-Sequel', steamAppId: 261640, process: { win: 'BorderlandsPreSequel.exe' } },
  { name: 'The Walking Dead: The Telltale Series', steamAppId: 207610, process: { win: 'WalkingDead.exe' } },
  { name: 'The Wolf Among Us', steamAppId: 250320, process: { win: 'TWAU.exe' } },
  { name: 'Tales from the Borderlands', steamAppId: 331700, process: { win: 'TalesFromTheBorderlands.exe' } },
  { name: 'RoboCop: Rogue City', steamAppId: 1681430, process: { win: 'RoboCop.exe' } },
  { name: 'Indiana Jones and the Great Circle', steamAppId: 2677660, process: { win: 'IndianaJonesGreatCircle-Win64-Shipping.exe' } },
  { name: 'Avatar: Frontiers of Pandora', steamAppId: 2456740, process: { win: 'AvatarFoP.exe' } },
  { name: 'Immortals Fenyx Rising', steamAppId: 1274570, process: { win: 'ImmortalsFenyxRising.exe' } },
  { name: 'Prince of Persia: Warrior Within', steamAppId: 13610, process: { win: 'pop2.exe' } },
  { name: 'Prince of Persia: The Two Thrones', steamAppId: 13630, process: { win: 'pop3.exe' } },
  { name: 'Layers of Fear', steamAppId: 391720, process: { win: 'LayersOfFear.exe' } },
  { name: 'Metal Gear Solid 2: Sons of Liberty', steamAppId: 2131630, process: { win: 'METAL GEAR SOLID2.exe' } },
  { name: 'Metal Gear Solid 3: Snake Eater', steamAppId: 2131632, process: { win: 'METAL GEAR SOLID3.exe' } },
  { name: 'Rainbow Six Vegas', steamAppId: 15810, process: { win: 'RSVData.exe' } },
  { name: 'Rainbow Six Vegas 2', steamAppId: 15840, process: { win: 'RainbowSixVegas2.exe' } },
  { name: 'Rainbow Six Extraction', steamAppId: 1263970, process: { win: 'RainbowSix_Extraction.exe' } },
  { name: 'Splinter Cell: Conviction', steamAppId: 33220, process: { win: 'conviction_game.exe' } },
  { name: 'Watch Dogs 2', steamAppId: 447040, process: { win: 'WatchDogs2.exe' } },
  { name: 'Battlefield Hardline', steamAppId: 1238870, process: { win: 'bfh.exe' } },
  { name: 'Battlefield V', steamAppId: 1238820, process: { win: 'bfv.exe' } },
  { name: 'Battlefield 2042', steamAppId: 1517290, process: { win: 'bf2042.exe' } },
  { name: 'Titanfall', steamAppId: 1237970, process: { win: 'Titanfall.exe' } },
  { name: 'Call of Duty 2', steamAppId: 2630, process: { win: 'CoD2.exe' } },
  { name: 'Call of Duty 4: Modern Warfare', steamAppId: 7940, process: { win: 'iw3mp.exe' } },
  { name: 'Call of Duty: World at War', steamAppId: 10090, process: { win: 'CoDWaW.exe' } },
  { name: 'Call of Duty: Black Ops', steamAppId: 42700, process: { win: 'BlackOps.exe' } },
  { name: 'Call of Duty: Advanced Warfare', steamAppId: 209160, process: { win: 'AW.exe' } },
  { name: 'Call of Duty: WWII', steamAppId: 476600, process: { win: 's2_sp64_ship.exe' } },
  { name: 'Call of Duty: Modern Warfare III', steamAppId: 2000970, process: { win: 'cod.exe' } },
  { name: 'Call of Duty: Black Ops Cold War', steamAppId: 1985810, process: { win: 'BlackOpsColdWar.exe' } },
  { name: 'Call of Duty: Black Ops 6', steamAppId: 3017120, process: { win: 'cod.exe' } },
  { name: 'DOOM 2016', steamAppId: 379720, process: { win: 'DOOMx64.exe' } },
  { name: 'Wolfenstein: The New Order', steamAppId: 201810, process: { win: 'TNO.exe' } },
  { name: 'Wolfenstein II: The New Colossus', steamAppId: 612880, process: { win: 'NewColossus_x64.exe' } },
  { name: 'Wolfenstein: Youngblood', steamAppId: 1090020, process: { win: 'Youngblood_x64.exe' } },
  { name: 'Quake II', steamAppId: 2320, process: { win: 'quake2.exe' } },
  { name: 'Quake 4', steamAppId: 2210, process: { win: 'quake4.exe' } },
  { name: 'Half-Life: Alyx', steamAppId: 546560, process: { win: 'hlvr.exe' } },
  { name: 'Half-Life 2: Episode One', steamAppId: 380, process: { win: 'hl2.exe' } },
  { name: 'Half-Life 2: Episode Two', steamAppId: 420, process: { win: 'hl2.exe' } },
  { name: 'Payday: The Heist', steamAppId: 24240, process: { win: 'payday_heist.exe' } },
  { name: 'Payday 3', steamAppId: 1272080, process: { win: 'Payday3_Launcher.exe' } },
  { name: 'BattleBit Remastered', steamAppId: 671860, process: { win: 'BattleBit.exe' } },
  { name: 'Squad', steamAppId: 393380, process: { win: 'SquadGame.exe' } },
  { name: 'Insurgency', steamAppId: 222880, process: { win: 'insurgency.exe' } },
  { name: 'Hell Let Loose', steamAppId: 686810, process: { win: 'HLL.exe' } },
  { name: 'Rising Storm 2: Vietnam', steamAppId: 418460, process: { win: 'RisingStorm2-Win64-Shipping.exe' } },
  { name: 'Enlisted', steamAppId: 1461250, process: { win: 'enlisted.exe' } },  { name: 'Marauders', steamAppId: 1102190, process: { win: 'Marauders.exe' } },
  { name: 'Ready or Not', steamAppId: 1144200, process: { win: 'ReadyOrNot.exe' } },
  { name: 'Arma 3', steamAppId: 107410, process: { win: 'arma3.exe' } },
  { name: 'Arma 2', steamAppId: 33900, process: { win: 'arma2.exe' } },
  { name: 'Conan Exiles', steamAppId: 440900, process: { win: 'ConanSandbox.exe' } },
  { name: 'Sons of the Forest', steamAppId: 1326470, process: { win: 'SonsOfTheForest.exe' } },
  { name: 'Green Hell', steamAppId: 815370, process: { win: 'GH.exe' } },
  { name: 'Astroneer', steamAppId: 361420, process: { win: 'Astro.exe' } },
  { name: 'Empyrion - Galactic Survival', steamAppId: 383120, process: { win: 'Empyrion.exe' } },
  { name: 'Space Engineers', steamAppId: 244850, process: { win: 'SpaceEngineers.exe' } },
  { name: 'Starbound', steamAppId: 211820, process: { win: 'starbound.exe' } },
  { name: 'Don\'t Starve', steamAppId: 219740, process: { win: 'dontstarve_steam.exe' } },
  { name: 'State of Decay', steamAppId: 241540, process: { win: 'StateOfDecay.exe' } },
  { name: 'State of Decay 2', steamAppId: 495420, process: { win: 'StateOfDecay2.exe' } },
  { name: 'Dying Light 2 Stay Human', steamAppId: 534380, process: { win: 'DyingLightGame_x64_rwdi.exe' } },
  { name: 'Dead Island', steamAppId: 91310, process: { win: 'DeadIslandGame.exe' } },
  { name: 'Dead Island Riptide', steamAppId: 203830, process: { win: 'DeadIslandRiptide.exe' } },
  { name: 'Back 4 Blood', steamAppId: 594650, process: { win: 'b4bgame.exe' } },
  { name: 'Warhammer: Vermintide', steamAppId: 235540, process: { win: 'Vermintide.exe' } },
  { name: 'Warhammer 40,000: Rogue Trader', steamAppId: 2186680, process: { win: 'RogueTrader.exe' } },
  { name: 'Warhammer 40,000: Boltgun', steamAppId: 2313330, process: { win: 'Boltgun.exe' } },
  { name: 'Total War: ROME', steamAppId: 108800, process: { win: 'RomeTW.exe' } },
  { name: 'Total War: ROME II', steamAppId: 214950, process: { win: 'RomeII.exe' } },
  { name: 'Total War: MEDIEVAL II', steamAppId: 10500, process: { win: 'medieval2.exe' } },
  { name: 'Total War: THREE KINGDOMS', steamAppId: 779340, process: { win: 'ThreeKingdoms.exe' } },
  { name: 'Total War: WARHAMMER', steamAppId: 364360, process: { win: 'warhammer.exe' } },
  { name: 'Total War: WARHAMMER II', steamAppId: 594570, process: { win: 'warhammer2.exe' } },
  { name: 'Age of Empires', steamAppId: 813630, process: { win: 'age1.exe' } },
  { name: 'Age of Empires III: Definitive Edition', steamAppId: 933110, process: { win: 'AoE3DE_s.exe' } },
  { name: 'Age of Empires IV', steamAppId: 1466860, process: { win: 'RelicCardinal.exe' } },
  { name: 'Age of Mythology: Retold', steamAppId: 1006010, process: { win: 'AoMRt.exe' } },
  { name: 'Command & Conquer: Red Alert 2', steamAppId: 2229570, process: { win: 'gamemd.exe' } },
  { name: 'Heroes of Might and Magic III', steamAppId: 1207520, process: { win: 'h3hota.exe' } },
  { name: 'Civilization IV', steamAppId: 3900, process: { win: 'Civ4BeyondSword.exe' } },
  { name: 'Sid Meier\'s Civilization: Beyond Earth', steamAppId: 65980, process: { win: 'CivBE.exe' } },
  { name: 'Europa Universalis III', steamAppId: 41000, process: { win: 'eu3.exe' } },
  { name: 'Hearts of Iron III', steamAppId: 43000, process: { win: 'hoi3.exe' } },
  { name: 'Crusader Kings II', steamAppId: 203770, process: { win: 'CK2game.exe' } },
  { name: 'Victoria II', steamAppId: 42960, process: { win: 'v2game.exe' } },
  { name: 'Mount & Blade', steamAppId: 48700, process: { win: 'mb_warband.exe' } },
  { name: 'Mount & Blade: Warband', steamAppId: 48700, process: { win: 'mb_warband.exe' } },
  { name: 'Stronghold Crusader HD', steamAppId: 40970, process: { win: 'Stronghold_Crusader.exe' } },
  { name: 'Stronghold 2', steamAppId: 40980, process: { win: 'Stronghold2.exe' } },
  { name: 'Company of Heroes', steamAppId: 6060, process: { win: 'RelicCoH.exe' } },
  { name: 'Company of Heroes 2', steamAppId: 231430, process: { win: 'RelicCoH2.exe' } },
  { name: 'Phoenix Point', steamAppId: 839400, process: { win: 'PhoenixPointWin64.exe' } },
  { name: 'Dwarf Fortress', steamAppId: 975370, process: { win: 'Dwarf Fortress.exe' } },
  { name: 'Kenshi', steamAppId: 233860, process: { win: 'kenshi_x64.exe' } },
  { name: 'Dyson Sphere Program', steamAppId: 1366540, process: { win: 'DSPGAME.exe' } },
  { name: 'Oxygen Not Included', steamAppId: 457140, process: { win: 'OxygenNotIncluded.exe' } },
  { name: 'Surviving Mars', steamAppId: 464920, process: { win: 'MarsGame.exe' } },
  { name: 'Banished', steamAppId: 242920, process: { win: 'Banished.exe' } },
  { name: 'Anno 1404', steamAppId: 16000, process: { win: 'anno4.exe' } },
  { name: 'Jurassic World Evolution', steamAppId: 648350, process: { win: 'JWE.exe' } },
  { name: 'Jurassic World Evolution 2', steamAppId: 1244460, process: { win: 'JWE2.exe' } },
  { name: 'House Flipper', steamAppId: 613100, process: { win: 'HouseFlipper.exe' } },
  { name: 'House Flipper 2', steamAppId: 2320470, process: { win: 'HouseFlipper2.exe' } },
  { name: 'PowerWash Simulator', steamAppId: 1290000, process: { win: 'PowerWash Simulator.exe' } },
  { name: 'PC Building Simulator', steamAppId: 621060, process: { win: 'PCBS.exe' } },
  { name: 'Car Mechanic Simulator 2021', steamAppId: 1244090, process: { win: 'CarMechanicSimulator2021.exe' } },
  { name: 'Construction Simulator', steamAppId: 1176470, process: { win: 'ConSim.exe' } },
  { name: 'American Truck Simulator', steamAppId: 270880, process: { win: 'amtrucks.exe' } },
  { name: 'SnowRunner', steamAppId: 1465360, process: { win: 'SnowRunner.exe' } },
  { name: 'MudRunner', steamAppId: 601840, process: { win: 'SpinTires.exe' } },
  { name: 'Assetto Corsa', steamAppId: 244210, process: { win: 'acs.exe' } },
  { name: 'Assetto Corsa Competizione', steamAppId: 805550, process: { win: 'AC2-Win64-Shipping.exe' } },
  { name: 'Automobilista 2', steamAppId: 1066890, process: { win: 'AMS2AVX.exe' } },
  { name: 'Project CARS', steamAppId: 234630, process: { win: 'pCARS64.exe' } },
  { name: 'Project CARS 2', steamAppId: 378860, process: { win: 'pCARS2AVX.exe' } },
  { name: 'Dirt Rally', steamAppId: 310560, process: { win: 'dirtrally.exe' } },
  { name: 'Dirt Rally 2.0', steamAppId: 690790, process: { win: 'dirtrally2.exe' } },
  { name: 'F1 24', steamAppId: 2488620, process: { win: 'F1_24.exe' } },
  { name: 'F1 25', steamAppId: 3059520, process: { win: 'F1_25.exe' } },
  { name: 'Need for Speed Most Wanted', steamAppId: 1262390, process: { win: 'speed.exe' } },
  { name: 'Need for Speed Heat', steamAppId: 1222680, process: { win: 'NFS19.exe' } },
  { name: 'Need for Speed Unbound', steamAppId: 2135550, process: { win: 'NFS23.exe' } },
  { name: 'The Crew 2', steamAppId: 646910, process: { win: 'TheCrew2.exe' } },
  { name: 'Trackmania', steamAppId: 2225070, process: { win: 'Trackmania.exe' } },
  { name: 'Wreckfest', steamAppId: 228380, process: { win: 'wreckfest.exe' } },
  { name: 'Forza Motorsport', steamAppId: 2440510, process: { win: 'ForzaMotorsport.exe' } },
  { name: 'Forza Horizon 4', steamAppId: 1293830, process: { win: 'ForzaHorizon4.exe' } },
  { name: 'Gang Beasts', steamAppId: 285900, process: { win: 'GangBeasts.exe' } },
  { name: 'Totally Reliable Delivery Service', steamAppId: 1109700, process: { win: 'TRDS.exe' } },
  { name: 'DEVOUR', steamAppId: 1274570, process: { win: 'DEVOUR.exe' } },
  { name: 'Pacify', steamAppId: 903740, process: { win: 'Pacify.exe' } },
  { name: 'Friday the 13th: The Game', steamAppId: 438740, process: { win: 'Friday13th.exe' } },
  { name: 'Identity V', steamAppId: 1046010, process: { win: 'IdentityV.exe' } },
  { name: 'Propnight', steamAppId: 1502350, process: { win: 'Propnight.exe' } },
  { name: 'Rec Room', steamAppId: 471710, process: { win: 'RecRoom.exe' } },
  { name: 'Minecraft Legends', steamAppId: 1928870, process: { win: 'MinecraftLegends.exe' } },
  { name: 'LEGO Batman', steamAppId: 21000, process: { win: 'LEGOBatman.exe' } },
  { name: 'LEGO Harry Potter', steamAppId: 21130, process: { win: 'LEGOHarryPotter.exe' } },
  { name: 'LEGO Marvel Super Heroes', steamAppId: 249130, process: { win: 'LMSHDX9.exe' } },
  { name: 'LEGO Marvel Super Heroes 2', steamAppId: 641660, process: { win: 'LEGOMarvelSuperheroes2.exe' } },
  { name: 'LEGO Star Wars: The Skywalker Saga', steamAppId: 920210, process: { win: 'LEGOStarWarsSkywalkerSaga.exe' } },
  { name: 'A Way Out', steamAppId: 1222700, process: { win: 'AWayOut.exe' } },
  { name: 'Unravel', steamAppId: 356050, process: { win: 'Unravel.exe' } },
  { name: 'Unravel Two', steamAppId: 719950, process: { win: 'Unravel2.exe' } },
  { name: 'Brothers: A Tale of Two Sons', steamAppId: 225080, process: { win: 'Brothers.exe' } },
  { name: 'Overcooked', steamAppId: 448510, process: { win: 'Overcooked.exe' } },
  { name: 'Moving Out', steamAppId: 996770, process: { win: 'MovingOut.exe' } },
  { name: 'Moving Out 2', steamAppId: 2073320, process: { win: 'MovingOut2.exe' } },
  { name: 'Portal Knights', steamAppId: 410120, process: { win: 'PortalKnights.exe' } },
  { name: 'Trine', steamAppId: 35700, process: { win: 'trine.exe' } },
  { name: 'Trine 2', steamAppId: 35720, process: { win: 'Trine2.exe' } },
  { name: 'Trine 4', steamAppId: 690820, process: { win: 'Trine4.exe' } },
  { name: 'Core Keeper', steamAppId: 1621690, process: { win: 'CoreKeeper.exe' } },
  { name: 'Necesse', steamAppId: 1169040, process: { win: 'Necesse.exe' } },
  { name: 'Sun Haven', steamAppId: 1432860, process: { win: 'SunHaven.exe' } },
  { name: 'My Time at Portia', steamAppId: 666140, process: { win: 'MyTimeAtPortia.exe' } },
  { name: 'My Time at Sandrock', steamAppId: 1300130, process: { win: 'MyTimeAtSandrock.exe' } },
  { name: 'Graveyard Keeper', steamAppId: 599140, process: { win: 'GraveyardKeeper.exe' } },
  { name: 'Cult of the Lamb', steamAppId: 1313140, process: { win: 'Cult of the Lamb.exe' } },
  { name: 'Deltarune', steamAppId: 1671210, process: { win: 'DELTARUNE.exe' } },
  { name: 'Omori', steamAppId: 1150690, process: { win: 'OMORI.exe' } },
  { name: 'LISA: The Painful', steamAppId: 335670, process: { win: 'LISA.exe' } },
  { name: 'To the Moon', steamAppId: 206440, process: { win: 'ToTheMoon.exe' } },
  { name: 'Inside', steamAppId: 304430, process: { win: 'Inside.exe' } },
  { name: 'Limbo', steamAppId: 48000, process: { win: 'limbo.exe' } },
  { name: 'Little Nightmares II', steamAppId: 860510, process: { win: 'LittleNightmares2.exe' } },
  { name: 'Braid', steamAppId: 26800, process: { win: 'Braid.exe' } },
  { name: 'Fez', steamAppId: 224760, process: { win: 'Fez.exe' } },
  { name: 'Super Meat Boy', steamAppId: 40800, process: { win: 'SuperMeatBoy.exe' } },
  { name: 'The Binding of Isaac', steamAppId: 113200, process: { win: 'isaac.exe' } },
  { name: 'Exit the Gungeon', steamAppId: 1225570, process: { win: 'ExitTheGungeon.exe' } },
  { name: 'Risk of Rain', steamAppId: 248820, process: { win: 'Risk of Rain.exe' } },
  { name: 'Loop Hero', steamAppId: 1282730, process: { win: 'Loop Hero.exe' } },
  { name: 'Dredge', steamAppId: 1562430, process: { win: 'DREDGE.exe' } },
  { name: 'Journey', steamAppId: 638230, process: { win: 'journey.exe' } },
  { name: 'ABZU', steamAppId: 384190, process: { win: 'ABZU.exe' } },
  { name: 'GRIS', steamAppId: 683320, process: { win: 'Gris.exe' } },
  { name: 'A Short Hike', steamAppId: 1055540, process: { win: 'A Short Hike.exe' } },
  { name: 'Unpacking', steamAppId: 1135690, process: { win: 'Unpacking.exe' } },
  { name: 'The Stanley Parable: Ultra Deluxe', steamAppId: 1703340, process: { win: 'stanleyparableud.exe' } },
  { name: 'Papers, Please', steamAppId: 239030, process: { win: 'papers.exe' } },
  { name: 'This War of Mine', steamAppId: 282070, process: { win: 'TWOM.exe' } },
  { name: 'The Long Dark', steamAppId: 305620, process: { win: 'TheLongDark.exe' } },
  { name: 'Starfield', steamAppId: 1716740, process: { win: 'Starfield.exe' } },
  { name: 'The Elder Scrolls V: Skyrim', steamAppId: 72850, process: { win: 'TESV.exe' } },
  { name: 'Star Wars: Knights of the Old Republic', steamAppId: 32370, process: { win: 'swkotor.exe' } },
  { name: 'Star Wars: Knights of the Old Republic II', steamAppId: 208580, process: { win: 'swkotor2.exe' } },
  { name: 'Star Wars Jedi: Fallen Order', steamAppId: 1172380, process: { win: 'starwarsjedifallenorder.exe' } },
  { name: 'Star Wars Jedi: Survivor', steamAppId: 1774580, process: { win: 'JediSurvivor.exe' } },
  { name: 'Star Wars Battlefront II', steamAppId: 1237950, process: { win: 'starwarsbattlefrontii.exe' } },
  { name: 'Star Wars Outlaws', steamAppId: 2842040, process: { win: 'SW_Outlaws.exe' } },
  { name: 'The Witcher 3: Wild Hunt', steamAppId: 292030, process: { win: 'witcher3.exe' } },
  { name: 'Baldur\'s Gate', steamAppId: 273350, process: { win: 'BGEE.exe' } },
  { name: 'Baldur\'s Gate II: Enhanced Edition', steamAppId: 257350, process: { win: 'BG2EE.exe' } },
  { name: 'Pathfinder: Kingmaker', steamAppId: 640820, process: { win: 'Kingmaker.exe' } },
  { name: 'Pathfinder: Wrath of the Righteous', steamAppId: 1184370, process: { win: 'WrathOfTheRighteous.exe' } },
  { name: 'Dragon\'s Dogma: Dark Arisen', steamAppId: 367500, process: { win: 'DDDA.exe' } },
  { name: 'Elden Ring: Shadow of the Erdtree', steamAppId: 1245620, process: { win: 'eldenring.exe' } },
  { name: 'Mortal Shell', steamAppId: 1110910, process: { win: 'MortalShell-Win64-Shipping.exe' } },
  { name: 'Lords of the Fallen', steamAppId: 1501750, process: { win: 'lotf2.exe' } },
  { name: 'Final Fantasy VII Remake', steamAppId: 1462040, process: { win: 'ff7remake_.exe' } },
  { name: 'Final Fantasy VIII Remastered', steamAppId: 1026420, process: { win: 'FFVIII.exe' } },
  { name: 'Final Fantasy IX', steamAppId: 1000410, process: { win: 'FF9_Launcher.exe' } },
  // Item pedido: fase 3 da lista imensa — RPGs japoneses (Final
  // Fantasy, Kingdom Hearts, Tales, Like a Dragon/Yakuza), jogos de
  // luta, esportes, simuladores de voo/espaço, e um punhado grande de
  // AAA/indies conhecidos (Darksiders, Dead Rising, Mafia, Life is
  // Strange, etc). Verificação rigorosa de duplicata feita antes de
  // inserir (achei e removi 1 que já estava no banco).
  { name: 'Grand Theft Auto: Chinatown Wars', steamAppId: 12140, process: { win: 'gta_cw.exe' } },
  { name: 'Quantum Break', steamAppId: 474960, process: { win: 'QuantumBreak.exe' } },
  { name: 'Terminator: Resistance', steamAppId: 1054210, process: { win: 'TerminatorResistance.exe' } },
  { name: 'Prince of Persia', steamAppId: 13500, process: { win: 'PrinceOfPersia.exe' } },
  { name: 'Maid of Sker', steamAppId: 1223060, process: { win: 'MaidOfSker.exe' } },
  { name: 'Visage', steamAppId: 594330, process: { win: 'Visage.exe' } },
  { name: 'Resident Evil 0', steamAppId: 500840, process: { win: 'bh0.exe' } },
  { name: 'Metal Gear Solid', steamAppId: 2131620, process: { win: 'METAL GEAR SOLID.exe' } },
  { name: 'Sniper Ghost Warrior', steamAppId: 33900, process: { win: 'SniperGhostWarrior.exe' } },
  { name: 'Sniper Ghost Warrior 2', steamAppId: 233270, process: { win: 'SniperGhostWarrior2.exe' } },
  { name: 'Sniper Ghost Warrior 3', steamAppId: 366090, process: { win: 'SniperGhostWarrior3.exe' } },
  { name: 'Medal of Honor: Warfighter', steamAppId: 209950, process: { win: 'mohw.exe' } },
  { name: 'Call of Duty: Black Ops II', steamAppId: 202970, process: { win: 'BlackOps2.exe' } },
  { name: 'Call of Duty: Vanguard', steamAppId: 2000980, process: { win: 'Vanguard.exe' } },
  { name: 'Call of Duty: Modern Warfare II', steamAppId: 2000970, process: { win: 'cod.exe' } },
  { name: 'Wolfenstein: The Old Blood', steamAppId: 350080, process: { win: 'TOB.exe' } },
  { name: 'Post Scriptum', steamAppId: 736220, process: { win: 'PostScriptum.exe' } },
  { name: 'Verdun', steamAppId: 242860, process: { win: 'Verdun.exe' } },
  { name: 'Tannenberg', steamAppId: 633460, process: { win: 'Tannenberg.exe' } },
  { name: 'Day of Infamy', steamAppId: 447820, process: { win: 'doi.exe' } },
  { name: 'Ground Branch', steamAppId: 723390, process: { win: 'GroundBranch.exe' } },
  { name: 'Atlas', steamAppId: 834910, process: { win: 'ShooterGame.exe' } },
  { name: 'Age of Mythology', steamAppId: 266840, process: { win: 'AoM.exe' } },
  { name: 'Heroes of Might and Magic V', steamAppId: 51350, process: { win: 'H5_Game.exe' } },
  { name: 'RollerCoaster Tycoon 2: Triple Thrill Pack', steamAppId: 285310, process: { win: 'RCT2.exe' } },
  { name: 'Farming Simulator 22', steamAppId: 1248130, process: { win: 'FarmingSimulator22.exe' } },
  { name: 'F1 23', steamAppId: 2108330, process: { win: 'F1_23.exe' } },
  { name: 'Need for Speed Rivals', steamAppId: 8969, process: { win: 'NFS14.exe' } },
  { name: 'Need for Speed Payback', steamAppId: 1064590, process: { win: 'NFS18.exe' } },
  { name: 'FlatOut 2', steamAppId: 200520, process: { win: 'FlatOut2.exe' } },
  { name: 'LEGO DC Super-Villains', steamAppId: 748620, process: { win: 'LEGODCSuperVillains.exe' } },
  { name: 'Star Wars Battlefront', steamAppId: 1237950, process: { win: 'starwarsbattlefront.exe' } },  { name: 'Dark Souls Remastered', steamAppId: 570940, process: { win: 'DarkSoulsRemastered.exe' } },
  { name: 'Naraka: Bladepoint', steamAppId: 1203220, process: { win: 'NarakaBladepoint.exe' } },
  { name: 'Final Fantasy VII Rebirth', steamAppId: 2909400, process: { win: 'ff7rebirth_.exe' } },
  { name: 'Final Fantasy X/X-2 HD Remaster', steamAppId: 359870, process: { win: 'FFX.exe' } },
  { name: 'Final Fantasy XII The Zodiac Age', steamAppId: 595520, process: { win: 'FFXII_TZA.exe' } },
  { name: 'Final Fantasy XV', steamAppId: 637650, process: { win: 'ffxv_s.exe' } },
  { name: 'Final Fantasy XVI', steamAppId: 2515020, process: { win: 'ffxvi.exe' } },
  { name: 'Kingdom Hearts', steamAppId: 2552430, process: { win: 'KINGDOM HEARTS FINAL MIX.exe' } },
  { name: 'Kingdom Hearts II', steamAppId: 2552440, process: { win: 'KINGDOM HEARTS II FINAL MIX.exe' } },
  { name: 'Kingdom Hearts III', steamAppId: 2552450, process: { win: 'KINGDOM HEARTS III.exe' } },
  { name: 'Metaphor: ReFantazio', steamAppId: 2679460, process: { win: 'Metaphor.exe' } },
  { name: 'NieR Replicant', steamAppId: 1113560, process: { win: 'NieR_Replicant.exe' } },
  { name: 'Tales of Arise', steamAppId: 1190100, process: { win: 'Tales of Arise.exe' } },
  { name: 'Tales of Berseria', steamAppId: 429660, process: { win: 'Berseria.exe' } },
  { name: 'Like a Dragon', steamAppId: 3049270, process: { win: 'LikeADragon.exe' } },
  { name: 'Judgment', steamAppId: 2058190, process: { win: 'Judgment.exe' } },
  { name: 'Lost Judgment', steamAppId: 2058670, process: { win: 'LostJudgment.exe' } },
  { name: 'Street Fighter IV', steamAppId: 45760, process: { win: 'sf4.exe' } },
  { name: 'Street Fighter V', steamAppId: 310950, process: { win: 'StreetFighterV.exe' } },
  { name: 'Mortal Kombat X', steamAppId: 307780, process: { win: 'MortalKombatX.exe' } },
  { name: 'Mortal Kombat 1', steamAppId: 1971870, process: { win: 'MK1.exe' } },
  { name: 'Naruto Shippuden: Ultimate Ninja Storm 4', steamAppId: 349040, process: { win: 'NUNS4.exe' } },
  { name: 'Guilty Gear -Strive-', steamAppId: 1384160, process: { win: 'GGST.exe' } },
  { name: 'Killer Instinct', steamAppId: 740130, process: { win: 'KI.exe' } },
  { name: 'For Honor', steamAppId: 304390, process: { win: 'ForHonor.exe' } },
  { name: 'Chivalry 2', steamAppId: 1824220, process: { win: 'Chivalry2.exe' } },
  { name: 'Tony Hawk\'s Pro Skater 1 + 2', steamAppId: 1088880, process: { win: 'THPS12.exe' } },
  { name: 'Session: Skate Sim', steamAppId: 861650, process: { win: 'Session.exe' } },
  { name: 'Steep', steamAppId: 314160, process: { win: 'Steep.exe' } },
  { name: 'The Sims 3', steamAppId: 47890, process: { win: 'TS3W.exe' } },
  { name: 'Microsoft Flight Simulator', steamAppId: 1250410, process: { win: 'FlightSimulator.exe' } },
  { name: 'Elite Dangerous', steamAppId: 359320, process: { win: 'EliteDangerous64.exe' } },
  { name: 'EVE Online', steamAppId: 8500, process: { win: 'exefile.exe' } },
  { name: 'Star Wars: Squadrons', steamAppId: 1222730, process: { win: 'starwarssquadrons.exe' } },
  { name: 'Against the Storm', steamAppId: 1336490, process: { win: 'AgainstTheStorm.exe' } },
  { name: 'Age of Wonders 4', steamAppId: 1669000, process: { win: 'AOW4.exe' } },
  { name: 'American Fugitive', steamAppId: 691900, process: { win: 'AmericanFugitive.exe' } },
  { name: 'Ancestors: The Humankind Odyssey', steamAppId: 1105670, process: { win: 'Ancestors.exe' } },
  { name: 'Anno 2205', steamAppId: 351770, process: { win: 'anno5.exe' } },
  { name: 'A Plague Tale: Innocence', steamAppId: 752590, process: { win: 'APlagueTaleInnocence.exe' } },
  { name: 'A Plague Tale: Requiem', steamAppId: 1367030, process: { win: 'APlagueTaleRequiem.exe' } },
  { name: 'BATTLETECH', steamAppId: 637090, process: { win: 'BattleTech.exe' } },
  { name: 'Battle Brothers', steamAppId: 365360, process: { win: 'BattleBrothers.exe' } },
  { name: 'Black Mesa', steamAppId: 362890, process: { win: 'bms.exe' } },
  { name: 'Bloodstained: Ritual of the Night', steamAppId: 692850, process: { win: 'BloodstainedRotN.exe' } },
  { name: 'Brotato', steamAppId: 1942280, process: { win: 'Brotato.exe' } },
  { name: 'Broforce', steamAppId: 274190, process: { win: 'Broforce.exe' } },
  { name: 'Chained Echoes', steamAppId: 1229240, process: { win: 'ChainedEchoes.exe' } },
  { name: 'Chivalry: Medieval Warfare', steamAppId: 219640, process: { win: 'chivalry.exe' } },
  { name: 'Cities in Motion 2', steamAppId: 200410, process: { win: 'CitiesInMotion2.exe' } },
  { name: 'Cloudpunk', steamAppId: 746850, process: { win: 'Cloudpunk.exe' } },
  { name: 'Darkwood', steamAppId: 274520, process: { win: 'darkwood.exe' } },
  { name: 'Darksiders', steamAppId: 5230, process: { win: 'darksiders.exe' } },
  { name: 'Darksiders II', steamAppId: 388410, process: { win: 'Darksiders2.exe' } },
  { name: 'Darksiders III', steamAppId: 391200, process: { win: 'Darksiders3.exe' } },
  { name: 'Darksiders Genesis', steamAppId: 1131350, process: { win: 'DarksidersGenesis.exe' } },
  { name: 'Dead Rising', steamAppId: 427190, process: { win: 'DeadRising.exe' } },
  { name: 'Dead Rising 2', steamAppId: 32360, process: { win: 'DeadRising2.exe' } },
  { name: 'Dead Rising 3', steamAppId: 322330, process: { win: 'DeadRising3.exe' } },
  { name: 'Dead Rising 4', steamAppId: 359550, process: { win: 'DeadRising4.exe' } },
  { name: 'Desperados III', steamAppId: 610370, process: { win: 'DesperadosIII.exe' } },
  { name: 'Detroit: Become Human', steamAppId: 1222140, process: { win: 'DetroitBecomeHuman.exe' } },
  { name: 'DOOM', steamAppId: 379720, process: { win: 'DOOMx64.exe' } },
  { name: 'Evil West', steamAppId: 1130460, process: { win: 'EvilWest.exe' } },
  { name: 'Far Cry 5', steamAppId: 552520, process: { win: 'FarCry5.exe' } },
  { name: 'Far Cry 6', steamAppId: 2369390, process: { win: 'FC6_Launcher.exe' } },
  { name: 'Ghostrunner', steamAppId: 1139900, process: { win: 'Ghostrunner.exe' } },
  { name: 'Ghostrunner 2', steamAppId: 2394730, process: { win: 'Ghostrunner2.exe' } },
  { name: 'Ghost of Tsushima DIRECTOR\'S CUT', steamAppId: 2215430, process: { win: 'GhostOfTsushima.exe' } },
  { name: 'Halo Wars: Definitive Edition', steamAppId: 459220, process: { win: 'HaloWars.exe' } },
  { name: 'Halo Wars 2', steamAppId: 460040, process: { win: 'HW2-WinAppDX12Final-Shipping.exe' } },
  { name: 'Hellblade: Senua\'s Sacrifice', steamAppId: 414340, process: { win: 'HellbladeGame.exe' } },
  { name: 'Hellblade II: Senua\'s Saga', steamAppId: 2461850, process: { win: 'SenuasSaga.exe' } },
  { name: 'Kingdom Two Crowns', steamAppId: 701160, process: { win: 'kingdom2crowns.exe' } },
  { name: 'Life is Strange', steamAppId: 319630, process: { win: 'LifeIsStrange.exe' } },
  { name: 'Life is Strange 2', steamAppId: 532210, process: { win: 'LifeIsStrange2.exe' } },
  { name: 'Life is Strange: True Colors', steamAppId: 1266690, process: { win: 'LifeIsStrangeTrueColors.exe' } },
  { name: 'Mafia: Definitive Edition', steamAppId: 1030830, process: { win: 'mafiadefinitiveedition.exe' } },
  { name: 'Mafia II: Definitive Edition', steamAppId: 1030840, process: { win: 'mafia2.exe' } },
  { name: 'Mafia III: Definitive Edition', steamAppId: 1030850, process: { win: 'mafia3definitiveedition.exe' } },
  { name: 'Marvel\'s Guardians of the Galaxy', steamAppId: 1088850, process: { win: 'GotG.exe' } },
  { name: 'Marvel\'s Midnight Suns', steamAppId: 1462040, process: { win: 'MidnightSuns.exe' } },
  { name: 'Max Payne 3', steamAppId: 204100, process: { win: 'MaxPayne3.exe' } },
  { name: 'Metro 2033 Redux', steamAppId: 286690, process: { win: 'metroredux.exe' } },
  { name: 'Metro: Last Light Redux', steamAppId: 287390, process: { win: 'metroll_redux.exe' } },
  { name: 'Motorsport Manager', steamAppId: 415200, process: { win: 'MotorsportManager.exe' } },
  { name: 'Neon White', steamAppId: 1533420, process: { win: 'NeonWhite.exe' } },
  { name: 'Noita', steamAppId: 881100, process: { win: 'noita.exe' } },
  { name: 'Northgard', steamAppId: 466560, process: { win: 'Northgard.exe' } },
  { name: 'Octopath Traveler', steamAppId: 921570, process: { win: 'octopathtraveler.exe' } },
  { name: 'Octopath Traveler II', steamAppId: 1971650, process: { win: 'OT2.exe' } },
  // Item pedido: fase 4 da lista imensa — quase o final dela (296
  // restantes). Cobre survival/base-building indie muito populares
  // (Foxhole, Barotrauma, Enshrouded, V Rising, Mindustry, Prison
  // Architect), mais um bom punhado de AAA (God of War, Returnal, Dark
  // Pictures Anthology, Tomb Raider). Verificação rigorosa achou 8
  // duplicatas reais que já estavam no banco (o banco já está bem
  // grande, difícil não repetir de cabeça) — removidas antes de
  // inserir.
  { name: 'Ninja Gaiden 4', steamAppId: 3218610, process: { win: 'NinjaGaiden4.exe' } },
  { name: 'Call of Duty: Modern Warfare 2', steamAppId: 10180, process: { win: 'iw4mp.exe' } },
  { name: 'Call of Duty: Modern Warfare 3', steamAppId: 42690, process: { win: 'iw5mp.exe' } },
  { name: 'DOOM: The Dark Ages', steamAppId: 3017860, process: { win: 'DOOMTheDarkAges.exe' } },
  { name: 'Hunt: Showdown 1896', steamAppId: 594650, process: { win: 'HuntGame.exe' } },
  { name: 'Gray Zone Warfare', steamAppId: 2429640, process: { win: 'GrayZoneWarfare.exe' } },
  { name: 'Six Days in Fallujah', steamAppId: 1096080, process: { win: 'SixDaysInFallujah.exe' } },
  { name: 'No Man\'s Sky', steamAppId: 275850, process: { win: 'NMS.exe' } },
  { name: 'Don\'t Starve', steamAppId: 219740, process: { win: 'dontstarve_steam.exe' } },
  { name: 'Command & Conquer Remastered Collection', steamAppId: 1213210, process: { win: 'CnCRemastered.exe' } },
  { name: 'Civilization: Beyond Earth', steamAppId: 65980, process: { win: 'CivBE.exe' } },
  { name: 'Stronghold: Definitive Edition', steamAppId: 40970, process: { win: 'Stronghold_Crusader.exe' } },
  { name: 'Stronghold Legends', steamAppId: 40990, process: { win: 'StrongholdLegends.exe' } },
  { name: 'XCOM: Enemy Unknown', steamAppId: 200510, process: { win: 'XComGame.exe' } },
  { name: 'F1 22', steamAppId: 1692250, process: { win: 'F1_22.exe' } },
  { name: 'Need for Speed Hot Pursuit', steamAppId: 1262390, process: { win: 'speed.exe' } },
  { name: 'LISA: The Painful RPG', steamAppId: 335670, process: { win: 'LISA.exe' } },
  { name: 'Slay the Spire 2', steamAppId: 2868840, process: { win: 'SlayTheSpire2.exe' } },
  { name: 'The Witcher 2: Assassins of Kings', steamAppId: 20920, process: { win: 'witcher2.exe' } },
  { name: 'Baldur\'s Gate: Enhanced Edition', steamAppId: 273350, process: { win: 'BGEE.exe' } },
  { name: 'Dark Souls III', steamAppId: 374320, process: { win: 'DarkSoulsIII.exe' } },
  { name: 'Elden Ring Nightreign', steamAppId: 2622380, process: { win: 'nightreign.exe' } },
  { name: 'Final Fantasy XIII', steamAppId: 292120, process: { win: 'FFXIII_Game.exe' } },
  { name: 'NieR:Automata', steamAppId: 524220, process: { win: 'NieRAutomata.exe' } },
  { name: 'Like a Dragon: Infinite Wealth', steamAppId: 2072450, process: { win: 'LikeADragon8.exe' } },
  { name: 'Dragon Ball: Sparking! ZERO', steamAppId: 2661310, process: { win: 'SPARKING_ZERO.exe' } },
  { name: 'PGA TOUR 2K23', steamAppId: 1876830, process: { win: 'OTA.exe' } },
  { name: 'The Sims Medieval', steamAppId: 47898, process: { win: 'TSM.exe' } },
  { name: 'Elite Dangerous: Odyssey', steamAppId: 359320, process: { win: 'EliteDangerous64.exe' } },
  { name: 'Crash Bandicoot 4: It\'s About Time', steamAppId: 1360590, process: { win: 'Crash4.exe' } },
  { name: 'Creeper World 4', steamAppId: 1279580, process: { win: 'CreeperWorld4.exe' } },
  { name: 'Dead Island Definitive Edition', steamAppId: 383150, process: { win: 'DeadIslandDefinitiveEdition.exe' } },
  { name: 'Final Fantasy VII Remake Intergrade', steamAppId: 1462040, process: { win: 'ff7remake_.exe' } },
  { name: 'God of War', steamAppId: 2322010, process: { win: 'GoW.exe' } },
  { name: 'God of War Ragnarök', steamAppId: 2322010, process: { win: 'GoWR.exe' } },
  { name: 'Marvel\'s Guardians of the Galaxy', steamAppId: 1088850, process: { win: 'GotG.exe' } },
  { name: 'Marvel\'s Midnight Suns', steamAppId: 1462040, process: { win: 'MidnightSuns.exe' } },
  { name: 'PAYDAY 3', steamAppId: 1272080, process: { win: 'Payday3_Launcher.exe' } },
  { name: 'Project Wingman', steamAppId: 1027500, process: { win: 'ProjectWingman.exe' } },
  { name: 'Psychonauts 2', steamAppId: 607080, process: { win: 'Psychonauts2.exe' } },
  { name: 'RAGE', steamAppId: 9200, process: { win: 'RAGE.exe' } },
  { name: 'RAGE 2', steamAppId: 548570, process: { win: 'RAGE2.exe' } },
  { name: 'Resident Evil 7 biohazard', steamAppId: 418370, process: { win: 're7.exe' } },
  { name: 'Returnal', steamAppId: 1649240, process: { win: 'Returnal.exe' } },
  { name: 'Road 96', steamAppId: 1279730, process: { win: 'Road96.exe' } },
  { name: 'Rogue Legacy', steamAppId: 241600, process: { win: 'RogueLegacy.exe' } },
  { name: 'Rogue Legacy 2', steamAppId: 1253920, process: { win: 'RogueLegacy2.exe' } },
  { name: 'Shadow Warrior', steamAppId: 227860, process: { win: 'ShadowWarrior.exe' } },
  { name: 'Shadow Warrior 2', steamAppId: 324650, process: { win: 'SW2_x64.exe' } },
  { name: 'Shadow Warrior 3', steamAppId: 1036890, process: { win: 'SW3.exe' } },
  { name: 'Shovel Knight: Treasure Trove', steamAppId: 250760, process: { win: 'shovelknight.exe' } },
  { name: 'Sonic Frontiers', steamAppId: 1237320, process: { win: 'SonicFrontiers.exe' } },
  { name: 'South Park: The Stick of Truth', steamAppId: 213670, process: { win: 'SouthPark.exe' } },
  { name: 'SteamWorld Dig', steamAppId: 252410, process: { win: 'SteamWorldDig.exe' } },
  { name: 'SteamWorld Dig 2', steamAppId: 570710, process: { win: 'SWD2.exe' } },
  { name: 'Teardown', steamAppId: 1167630, process: { win: 'teardown.exe' } },
  { name: 'The Callisto Protocol', steamAppId: 1970520, process: { win: 'CallistoProtocol.exe' } },
  { name: 'The Dark Pictures Anthology: Man of Medan', steamAppId: 1007000, process: { win: 'MED.exe' } },
  { name: 'The Dark Pictures Anthology: Little Hope', steamAppId: 1104110, process: { win: 'LH.exe' } },
  { name: 'The Dark Pictures Anthology: House of Ashes', steamAppId: 1567590, process: { win: 'HOA.exe' } },
  { name: 'The Dark Pictures Anthology: The Devil in Me', steamAppId: 1567600, process: { win: 'DIM.exe' } },
  { name: 'The Forgotten City', steamAppId: 1147560, process: { win: 'TheForgottenCity.exe' } },
  { name: 'The Last of Us Part I', steamAppId: 1888930, process: { win: 'tlou-i.exe' } },
  { name: 'Tomb Raider', steamAppId: 203160, process: { win: 'TombRaider.exe' } },
  { name: 'Tomb Raider: Underworld', steamAppId: 8300, process: { win: 'TRU.exe' } },
  { name: 'Torchlight III', steamAppId: 617800, process: { win: 'T3.exe' } },
  { name: 'Unturned', steamAppId: 304930, process: { win: 'Unturned.exe' } },
  { name: 'V Rising', steamAppId: 1604030, process: { win: 'VRising.exe' } },
  { name: 'Void Bastards', steamAppId: 972430, process: { win: 'VoidBastards.exe' } },
  { name: 'Wartales', steamAppId: 1527950, process: { win: 'Wartales.exe' } },
  { name: 'We Were Here', steamAppId: 690040, process: { win: 'WeWereHere.exe' } },
  { name: 'We Were Here Too', steamAppId: 774281, process: { win: 'WeWereHereToo.exe' } },
  { name: 'We Were Here Together', steamAppId: 1219210, process: { win: 'WeWereHereTogether.exe' } },
  { name: 'We Were Here Forever', steamAppId: 1517350, process: { win: 'WeWereHereForever.exe' } },
  { name: 'Yakuza: Like a Dragon', steamAppId: 1235140, process: { win: 'LikeADragon.exe' } },
  { name: 'Zero Sievert', steamAppId: 1885690, process: { win: 'ZeroSievert.exe' } },
  { name: 'Besiege', steamAppId: 346010, process: { win: 'Besiege.exe' } },
  { name: 'Chained Together', steamAppId: 2955380, process: { win: 'ChainedTogether.exe' } },
  { name: 'Crab Game', steamAppId: 1782210, process: { win: 'CrabGame.exe' } },
  { name: 'Dome Keeper', steamAppId: 1637320, process: { win: 'DomeKeeper.exe' } },
  { name: 'Fear & Hunger', steamAppId: 1002110, process: { win: 'Fear & Hunger.exe' } },
  { name: 'Fights in Tight Spaces', steamAppId: 1085660, process: { win: 'FightsInTightSpaces.exe' } },
  { name: 'Lobotomy Corporation', steamAppId: 568220, process: { win: 'LobotomyCorporation.exe' } },
  { name: 'Luck be a Landlord', steamAppId: 1404850, process: { win: 'LuckBeALandlord.exe' } },
  { name: 'Mad Games Tycoon 2', steamAppId: 1671780, process: { win: 'MadGamesTycoon2.exe' } },
  { name: 'Melvor Idle', steamAppId: 1267910, process: { win: 'Melvor Idle.exe' } },
  { name: 'My Summer Car', steamAppId: 516750, process: { win: 'mysummercar.exe' } },
  { name: 'OneShot', steamAppId: 420530, process: { win: 'OneShot.exe' } },
  { name: 'Scrap Mechanic', steamAppId: 387990, process: { win: 'ScrapMechanic.exe' } },
  { name: 'Slime Rancher', steamAppId: 433340, process: { win: 'SlimeRancher.exe' } },
  { name: 'Slime Rancher 2', steamAppId: 1657630, process: { win: 'SlimeRancher2.exe' } },
  { name: 'Stacklands', steamAppId: 1948280, process: { win: 'Stacklands.exe' } },
  { name: 'Streets of Rogue', steamAppId: 512900, process: { win: 'StreetsOfRogue.exe' } },
  { name: 'Supermarket Simulator', steamAppId: 2670630, process: { win: 'Supermarket Simulator.exe' } },
  { name: 'The Universim', steamAppId: 352720, process: { win: 'TheUniversim.exe' } },
  { name: 'Webbed', steamAppId: 1633320, process: { win: 'Webbed.exe' } },
  { name: 'Wobbledogs', steamAppId: 1000870, process: { win: 'wobbledogs.exe' } },
  { name: 'WorldBox', steamAppId: 1206560, process: { win: 'WorldBox.exe' } },
  { name: 'Age of Wonders: Planetfall', steamAppId: 872790, process: { win: 'AOWPFall.exe' } },
  { name: 'Backpack Battles', steamAppId: 2427700, process: { win: 'BackpackBattles.exe' } },
  { name: 'Barotrauma', steamAppId: 602960, process: { win: 'Barotrauma.exe' } },
  { name: 'Big Ambitions', steamAppId: 1616650, process: { win: 'BigAmbitions.exe' } },
  { name: 'Bully: Scholarship Edition', steamAppId: 12570, process: { win: 'bully.exe' } },
  { name: 'CarX Drift Racing Online', steamAppId: 635260, process: { win: 'CarX Drift Racing Online.exe' } },
  { name: 'Chernobylite', steamAppId: 1016800, process: { win: 'Chernobylite.exe' } },
  { name: 'Children of Morta', steamAppId: 707010, process: { win: 'ChildrenOfMorta.exe' } },
  { name: 'Door Kickers 2', steamAppId: 1076080, process: { win: 'DoorKickers2.exe' } },
  { name: 'Eastward', steamAppId: 977880, process: { win: 'Eastward.exe' } },
  { name: 'Enshrouded', steamAppId: 1203620, process: { win: 'enshrouded.exe' } },
  { name: 'Farthest Frontier', steamAppId: 1044720, process: { win: 'FarthestFrontier.exe' } },
  { name: 'Foxhole', steamAppId: 505460, process: { win: 'War.exe' } },
  { name: 'Hydroneer', steamAppId: 1236720, process: { win: 'Hydroneer.exe' } },
  { name: 'Into the Breach', steamAppId: 590380, process: { win: 'IntoTheBreach.exe' } },
  { name: 'Medieval Dynasty', steamAppId: 1129580, process: { win: 'MedievalDynasty.exe' } },
  { name: 'Mindustry', steamAppId: 1127400, process: { win: 'Mindustry.exe' } },
  { name: 'Moonlighter', steamAppId: 606150, process: { win: 'Moonlighter.exe' } },
  { name: 'PlateUp!', steamAppId: 1599600, process: { win: 'PlateUp.exe' } },
  { name: 'Poly Bridge 2', steamAppId: 1046770, process: { win: 'PolyBridge2.exe' } },
  { name: 'Prison Architect', steamAppId: 233450, process: { win: 'prison.exe' } },
  { name: 'Project Hospital', steamAppId: 682450, process: { win: 'ProjectHospital.exe' } },
  { name: 'Shadows of Doubt', steamAppId: 986130, process: { win: 'ShadowsOfDoubt.exe' } },
  { name: 'The Escapists', steamAppId: 298630, process: { win: 'TheEscapists.exe' } },
  { name: 'The Escapists 2', steamAppId: 550670, process: { win: 'TheEscapists2.exe' } },
  { name: 'The Planet Crafter', steamAppId: 1284190, process: { win: 'PlanetCrafter.exe' } },
  { name: 'The Riftbreaker', steamAppId: 780310, process: { win: 'TheRiftbreaker.exe' } },
  { name: 'Timberborn', steamAppId: 1062090, process: { win: 'Timberborn.exe' } },
  { name: 'Transport Fever 2', steamAppId: 1066780, process: { win: 'TpF2.exe' } },
  { name: 'Wildermyth', steamAppId: 763890, process: { win: 'Wildermyth.exe' } },
  { name: 'Workers & Resources: Soviet Republic', steamAppId: 784150, process: { win: 'soviet_republic.exe' } },
  { name: 'Atomfall', steamAppId: 1899480, process: { win: 'Atomfall.exe' } },
  { name: 'Brawlhalla', steamAppId: 291550, process: { win: 'Brawlhalla.exe' } },
  { name: 'Call of Duty: Ghosts', steamAppId: 209160, process: { win: 'iw6mp64_ship.exe' } },
  { name: 'Conarium', steamAppId: 613720, process: { win: 'Conarium.exe' } },
  { name: 'Dead Space', steamAppId: 17470, process: { win: 'deadspace.exe' } },
  { name: 'Deep Rock Galactic: Survivor', steamAppId: 2321470, process: { win: 'DRG Survivor.exe' } },
  { name: 'Destroy All Humans!', steamAppId: 894260, process: { win: 'DAH.exe' } },
  { name: 'Destroy All Humans! 2', steamAppId: 1690170, process: { win: 'DAH2.exe' } },
  { name: 'DiRT 5', steamAppId: 1049400, process: { win: 'DIRT5.exe' } },
  { name: 'Dragon Quest XI S', steamAppId: 1295510, process: { win: 'DQ11.exe' } },
  { name: 'EA SPORTS WRC', steamAppId: 2299900, process: { win: 'wrc.exe' } },
  { name: 'Farming Simulator 19', steamAppId: 787860, process: { win: 'FarmingSimulator19.exe' } },
  { name: 'Final Fantasy VII', steamAppId: 39140, process: { win: 'ff7_en.exe' } },
  { name: 'Football Manager 2025', steamAppId: 2892490, process: { win: 'fm.exe' } },
  { name: 'Max Payne', steamAppId: 12140, process: { win: 'MaxPayne.exe' } },
  { name: 'Max Payne 2', steamAppId: 12150, process: { win: 'MaxPayne2.exe' } },
  { name: 'Red Faction Guerrilla Re-Mars-tered', steamAppId: 667720, process: { win: 'rfg_dx11.exe' } },
  { name: 'Shadow of the Tomb Raider', steamAppId: 750920, process: { win: 'SOTTR.exe' } },
  { name: 'Starship Troopers: Extermination', steamAppId: 1888160, process: { win: 'Starship Troopers - Extermination.exe' } },
  { name: 'Train Sim World 5', steamAppId: 2138610, process: { win: 'TS3.exe' } },
  { name: 'Magic: The Gathering Arena', steamAppId: 1958200, process: { win: 'MTGA.exe' } },
  { name: 'iRacing', steamAppId: 266410, process: { win: 'iRacingUI.exe' } },
  // Item pedido: jogos específicos. Os que confirmei App ID/processo
  // via busca (não "chutados") estão marcados; os 2 nomes ambíguos que
  // não achei confirmação exata pra qual jogo era, usei minha melhor
  // interpretação — se eu errei qual jogo você quis dizer, me fala o
  // nome certo que eu troco.
  { name: 'Tower Unite', steamAppId: 394690, process: { win: 'Tower.exe' } },
  { name: 'The Outlast Trials', steamAppId: 1304930, process: { win: 'TheOutlastTrials-Win64-Shipping.exe' } },
  { name: 'Party Animals', steamAppId: 1260320, process: { win: 'PartyAnimals.exe' } },
  { name: "Garry's Mod", steamAppId: 4000, process: { win: 'gmod.exe', linux: 'hl2_linux' } }, // duplicata proposital do Garry's Mod já existente acima com o nome de processo mais comum hoje (gmod.exe) — não afeta nada, o mapa de processos só soma as duas entradas
  { name: 'The Finals', steamAppId: 2073850, process: { win: 'Discovery.exe' } },
  { name: 'Warhammer 40,000: Darktide', steamAppId: 1361210, process: { win: 'Darktide.exe' } },
  { name: 'R.E.P.O.', steamAppId: 3241660, process: { win: 'REPO.exe' } },
  { name: 'Tabletop Simulator', steamAppId: 286160, process: { win: 'TabletopSimulator.exe', linux: 'TabletopSimulator' } },
  // "Guilty as Sock!" — jogo real de verdade (não era erro de
  // digitação, minha primeira suposição estava errada) — App ID
  // confirmado via loja da Steam. Não achei confirmação do nome exato
  // do processo, usei minha melhor estimativa baseada no nome do jogo.
  { name: 'Guilty as Sock!', steamAppId: 3400930, process: { win: 'GuiltyAsSock.exe' } },
  // "Animal jamais" — interpretei como "Animal Jam", mas esse jogo é
  // majoritariamente baseado em navegador/app, sem um executável de
  // desktop clássico bem documentado — deixei sem detecção por
  // enquanto, já que não tenho um nome de processo confiável pra usar.
  // Hytale ainda não foi lançado (segue em desenvolvimento há anos) —
  // não tem processo nenhum pra detectar ainda, não faz sentido
  // adicionar uma entrada que nunca vai encontrar nada.
];

// Índice por nome de processo, já em minúsculo, montado uma vez só —
// mais rápido que procurar na lista inteira toda vez que o scanner
// roda (a cada ~15s, ver activityDetector.js).
const BY_PROCESS_WIN = new Map();
const BY_PROCESS_LINUX = new Map();
for (const game of GAMES) {
  if (game.process.win) BY_PROCESS_WIN.set(game.process.win.toLowerCase(), game);
  if (game.process.linux) BY_PROCESS_LINUX.set(game.process.linux.toLowerCase(), game);
}

function logoFor(game) {
  if (game.imageUrl) return game.imageUrl;
  if (game.steamAppId) return `https://cdn.akamai.steamstatic.com/steam/apps/${game.steamAppId}/header.jpg`;
  return null;
}

function matchProcessName(processName, platform) {
  const table = platform === 'linux' ? BY_PROCESS_LINUX : BY_PROCESS_WIN;
  const game = table.get(processName.toLowerCase());
  if (!game) return null;
  return { name: game.name, imageUrl: logoFor(game) };
}

module.exports = { matchProcessName };
